import type { Lesson } from './types'

const r = String.raw

/** Algebra, trigonometry and calculus lessons — pure data on top of function-plot / surface-3d. */
export const maths: Lesson[] = [
  // ---------- algebra ----------
  {
    id: 'linear-equations',
    title: 'Linear equations: where two lines meet',
    subject: 'algebra',
    difficulty: 'beginner',
    equation: r`mx + b = k \;\Longleftrightarrow\; mx + b - k = 0`,
    summary: 'Solving $mx + b = k$ is exactly the same problem as finding where the line $y = mx + b - k$ crosses zero.',
    concepts: ['linear-function', 'root', 'slope-intercept'],
    prerequisites: ['function-graph'],
    related: ['quadratic-roots', 'slope'],
    visualization: { type: 'function-plot', options: { expr: 'm*x + b - k', domain: [-10, 10], range: [-10, 10], mode: 'plain' } },
    parameters: {
      m: { label: 'slope m', min: -3, max: 3, step: 0.1, value: 1 },
      b: { label: 'intercept b', min: -8, max: 8, step: 0.5, value: 2 },
      k: { label: 'target value k', min: -8, max: 8, step: 0.5, value: 5 },
      x: { label: 'x (drag until the curve hits zero)', min: -10, max: 10, step: 0.05, value: 0 },
    },
    variables: [
      { symbol: 'm', meaning: 'slope of the line' },
      { symbol: 'b', meaning: 'y-intercept' },
      { symbol: 'k', meaning: 'target value on the right-hand side' },
      { symbol: 'x', meaning: 'the unknown — where the plotted line crosses zero' },
    ],
    explanation: {
      intuition: [
        'Drag the point along the line and watch the readout for $f(x)$: solving $mx + b = k$ is nothing more than sliding $x$ until that readout hits zero, because the line you are dragging along is $y = mx + b - k$, the original equation with everything moved to one side.',
        'Change $b$ or $k$ and the whole line shifts up or down, so the crossing point slides sideways. Change $m$ and the line tilts — steeper slopes mean the same vertical shift moves the crossing a much shorter horizontal distance.',
      ],
      formal: [
        'For $m \\ne 0$, $mx + b = k$ has the unique solution $x = (k - b)/m$.',
        'The graph of $y = mx + b - k$ is a straight line with slope $m$ and $y$-intercept $b - k$; its unique zero is the solution.',
      ],
      advanced: ['When $m = 0$ the "line" is horizontal: if $b = k$ every $x$ satisfies the equation (infinitely many solutions), and if $b \\ne k$ no $x$ does. This is the case that distinguishes a genuinely first-degree equation from a degenerate one, and it recurs throughout linear algebra as the difference between a consistent and an inconsistent system.'],
    },
    derivation: [
      { tex: r`mx + b = k`, note: 'Start from the equation as given.' },
      { tex: r`mx + b - k = 0`, note: 'Move everything to one side — this is exactly the plotted curve.' },
      { tex: r`x = \frac{k - b}{m}`, note: 'Divide by $m$ (valid whenever $m \\ne 0$).' },
    ],
    realWorld: [
      { title: 'Break-even points', text: 'Cost and revenue are both linear in units sold; the break-even point is where the two lines meet.' },
      { title: 'Unit conversion', text: 'Fahrenheit and Celsius are related by a linear equation, $F = \\tfrac95 C + 32$.' },
      { title: 'Pricing plans', text: 'Two phone plans with different base fees and per-minute rates cross at the usage level where they cost the same.' },
      { title: 'Motion at constant speed', text: 'Position versus time is linear; finding when two vehicles meet is solving a linear equation.' },
    ],
  },
  {
    id: 'quadratic-roots',
    title: 'Quadratic roots and the discriminant',
    subject: 'algebra',
    difficulty: 'high-school',
    equation: r`ax^2 + bx + c = 0 \;\Longrightarrow\; x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`,
    summary: 'The sign of $b^2 - 4ac$ tells you, before solving anything, whether the parabola crosses the axis twice, touches it once, or misses it entirely.',
    concepts: ['quadratic-function', 'discriminant', 'parabola', 'root'],
    prerequisites: ['function-graph', 'linear-equations'],
    related: ['linear-equations', 'absolute-value-inequalities'],
    visualization: { type: 'function-plot', options: { expr: 'a*x^2 + b*x + c', domain: [-10, 10], range: [-12, 20], mode: 'tangent' } },
    parameters: {
      a: { label: 'a (curvature)', min: -3, max: 3, step: 0.1, value: 1 },
      b: { label: 'b', min: -8, max: 8, step: 0.1, value: -1 },
      c: { label: 'c', min: -10, max: 10, step: 0.5, value: -6 },
      x: { label: 'x (drag along the curve)', min: -10, max: 10, step: 0.05, value: 0 },
    },
    variables: [
      { symbol: 'a, b, c', meaning: 'coefficients of the quadratic' },
      { symbol: r`\Delta = b^2 - 4ac`, meaning: 'the discriminant — decides the number of real roots' },
      { symbol: 'x', meaning: 'point being dragged along the parabola' },
    ],
    explanation: {
      intuition: [
        'Drag the point across the curve: wherever it crosses the horizontal axis is a root. With the starting values you should see two crossings. Now shrink $c$ toward $0$ or shift the parabola upward with $b$ — watch the two crossings slide toward each other.',
        'Push the parabola up until it just kisses the axis at its vertex: that is the knife-edge case of exactly one root, where the tangent line at the crossing is horizontal. Push it further and the curve never returns to zero — no real roots, only complex ones.',
      ],
      formal: [
        'The roots are $x = \\dfrac{-b \\pm \\sqrt{\\Delta}}{2a}$ with $\\Delta = b^2 - 4ac$.',
        '$\\Delta > 0$ gives two distinct real roots, $\\Delta = 0$ gives one repeated root (the vertex touches the axis), and $\\Delta < 0$ gives no real roots.',
      ],
      advanced: ['When $\\Delta < 0$ the two roots are complex conjugates $\\dfrac{-b \\pm i\\sqrt{-\\Delta}}{2a}$; they still satisfy the same factorisation $a(x-r_1)(x-r_2)$, just off the real axis, which is why the parabola can miss the $x$-axis and yet the equation still "has" two roots.'],
    },
    derivation: [
      { tex: r`ax^2 + bx + c = 0 \;\Rightarrow\; x^2 + \frac{b}{a}x = -\frac{c}{a}`, note: 'Divide through by $a$.' },
      { tex: r`\left(x + \frac{b}{2a}\right)^2 = \frac{b^2 - 4ac}{4a^2}`, note: 'Complete the square on the left.' },
      { tex: r`x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}`, note: 'Take the square root of both sides and solve for $x$.' },
    ],
    realWorld: [
      { title: 'Projectile landing time', text: 'Height versus time under gravity is quadratic; the discriminant tells you whether a thrown ball ever reaches a given height.' },
      { title: 'Break-even with fixed and variable costs', text: 'Profit that includes a quadratic revenue term (price affects quantity sold) needs the quadratic formula to find zero-profit points.' },
      { title: 'Optics and antenna design', text: 'Focal properties of parabolic mirrors and dishes come from the same quadratic geometry.' },
      { title: 'Engineering tolerances', text: 'A design constraint with no real solution ($\\Delta < 0$) tells engineers a target is simply unreachable with the current parameters.' },
    ],
  },
  {
    id: 'exponents-and-powers',
    title: 'Power functions and fractional exponents',
    subject: 'algebra',
    difficulty: 'high-school',
    equation: r`f(x) = x^n`,
    summary: 'One exponent $n$ controls a whole family of curves — straight lines, parabolas, roots and reciprocals are all $x^n$ in disguise.',
    concepts: ['exponent', 'power-function', 'root'],
    prerequisites: ['function-graph'],
    related: ['logarithms', 'exponential-growth'],
    visualization: { type: 'function-plot', options: { expr: 'x^n', domain: [0.1, 4], range: [-2, 20], mode: 'plain' } },
    parameters: {
      n: { label: 'exponent n', min: -1, max: 3, step: 0.1, value: 2 },
      x: { label: 'x', min: 0.1, max: 4, step: 0.02, value: 2 },
    },
    variables: [
      { symbol: 'n', meaning: 'the exponent — can be negative or fractional' },
      { symbol: 'x', meaning: 'the base, restricted here to positive values' },
    ],
    explanation: {
      intuition: [
        'Slide $n$ from $2$ down to $1$: the parabola straightens into the line $y = x$. Keep going to $n = 0.5$ and the curve becomes a square root — steep near zero, flattening out — and at $n = 0$ it is simply the flat line $y = 1$.',
        'Push $n$ negative and the curve flips character completely: instead of growing, it now blows up as $x$ shrinks toward $0.1$ and settles down toward zero as $x$ grows, because $x^{-1} = 1/x$. The single formula $x^n$ quietly reproduces multiplication, roots and reciprocals just by turning one dial.',
      ],
      formal: [
        'For $x > 0$, $x^n$ is defined for every real $n$ via $x^n = e^{n \\ln x}$, so fractional and negative exponents are as legitimate as integer ones.',
        r`x^{p/q} = \sqrt[q]{x^p}` + ' (for positive integers $p, q$), and $x^{-n} = 1/x^n$.',
      ],
      advanced: ['Restricting to $x > 0$ is what makes $x^n = e^{n\\ln x}$ well defined for every real $n$; for negative $x$, non-integer powers generally leave the real numbers (e.g. $(-1)^{1/2} = i$), which is why this lesson keeps the domain positive.'],
    },
    derivation: [
      { tex: r`x^{a} \cdot x^{b} = x^{a+b}`, note: 'The defining law of exponents, true for integer $a, b$.' },
      { tex: r`x^{p/q} = \left(x^{1/q}\right)^{p}, \qquad \left(x^{1/q}\right)^q = x`, note: 'Extend to rationals: $x^{1/q}$ is defined as the $q$-th root.' },
      { tex: r`x^{n} := e^{n \ln x}\ (x>0)`, note: 'Extend to every real $n$ using the exponential, agreeing with the rational case.' },
    ],
    realWorld: [
      { title: 'Scaling laws', text: 'Surface area scales as length squared, volume as length cubed — both power functions of the same variable.' },
      { title: 'Inverse-square laws', text: 'Gravity and light intensity fall off as $x^{-2}$, a negative-exponent power function.' },
      { title: 'Allometry in biology', text: 'Metabolic rate scales roughly as (body mass)$^{3/4}$ — a fractional exponent.' },
      { title: 'Engineering safety factors', text: 'Stress in a beam can scale with a fractional power of its dimensions, guiding how much a design can shrink or grow.' },
    ],
  },
  {
    id: 'logarithms',
    title: 'Logarithms as the inverse of powers',
    subject: 'algebra',
    difficulty: 'high-school',
    equation: r`y = \log_b x \;\Longleftrightarrow\; b^y = x`,
    summary: 'A logarithm answers "what power of $b$ gives $x$?" — it undoes exponentiation the way subtraction undoes addition.',
    concepts: ['logarithm', 'inverse-function', 'exponential'],
    prerequisites: ['exponents-and-powers'],
    related: ['exponential-growth', 'exponents-and-powers'],
    visualization: { type: 'function-plot', options: { expr: 'log(x, b)', domain: [0.1, 10], range: [-4, 4], mode: 'plain' } },
    charts: [{ title: 'The other half of the pair: b^x', xLabel: 'x', yLabel: 'b^x', domain: [-4, 4], marker: 'x', series: [{ label: 'y = b^x', expr: 'b^x' }] }],
    parameters: {
      b: { label: 'base b', min: 1.1, max: 5, step: 0.1, value: 2 },
      x: { label: 'x', min: 0.1, max: 10, step: 0.02, value: 4 },
    },
    variables: [
      { symbol: 'b', meaning: 'the base of the logarithm (and of the paired exponential)' },
      { symbol: 'x', meaning: 'the input to the logarithm, must be positive' },
    ],
    explanation: {
      intuition: [
        'Drag $x$ and read $y = \\log_b x$: it is the exponent you would need on $b$ to get back to $x$. Compare with the chart below, $b^x$ — the log curve is that same relationship read backwards, which is why the two curves are mirror images across $y = x$.',
        'Increase the base $b$ and the log curve flattens: it takes a much larger $x$ to reach the same output, because a bigger base reaches any given power faster. At $x = 1$ every log curve passes through zero, whatever the base — $b^0 = 1$ always.',
      ],
      formal: [
        '$y = \\log_b x$ is defined for $x > 0$ as the unique $y$ with $b^y = x$ ($b > 0$, $b \\ne 1$); it is the inverse function of $b^x$.',
        r`\log_b(xy) = \log_b x + \log_b y, \qquad \log_b(x^p) = p\log_b x.`,
      ],
      advanced: ['Because $\\log_b x = \\ln x / \\ln b$, every logarithm is a rescaling of the natural log; this is why calculators need only implement one logarithm and derive the rest, and why $d(\\log_b x)/dx = 1/(x\\ln b)$ carries an extra factor compared to the natural log.'],
    },
    derivation: [
      { tex: r`b^y = x`, note: 'Definition: $y$ is the exponent that turns $b$ into $x$.' },
      { tex: r`b^{y_1+y_2} = b^{y_1}b^{y_2} = x_1 x_2`, note: 'Exponent addition corresponds to multiplying the outputs.' },
      { tex: r`\log_b(x_1 x_2) = y_1 + y_2 = \log_b x_1 + \log_b x_2`, note: 'Taking logs turns multiplication into addition.' },
    ],
    realWorld: [
      { title: 'pH and the Richter scale', text: 'Both are base-10 logarithms of a quantity that spans many orders of magnitude, compressed into a manageable range.' },
      { title: 'Decibels', text: 'Sound intensity is perceived roughly logarithmically, so loudness is measured in a log scale.' },
      { title: 'Information theory', text: 'The number of bits needed to encode $N$ equally likely messages is $\\log_2 N$.' },
      { title: 'Solving for time in growth models', text: 'Doubling time or half-life comes from taking a logarithm of an exponential equation.' },
    ],
  },
  {
    id: 'absolute-value-inequalities',
    title: 'Absolute value inequalities',
    subject: 'algebra',
    difficulty: 'high-school',
    equation: r`|x - c| < r \;\Longleftrightarrow\; c - r < x < c + r`,
    summary: 'The inequality $|x-c| < r$ describes every point within distance $r$ of $c$ — exactly where the V-shaped curve $|x-c|-r$ dips below zero.',
    concepts: ['absolute-value', 'inequality', 'distance'],
    prerequisites: ['function-graph', 'linear-equations'],
    related: ['linear-equations', 'quadratic-roots'],
    visualization: { type: 'function-plot', options: { expr: 'abs(x - c) - r', domain: [-10, 10], range: [-6, 10], mode: 'plain' } },
    parameters: {
      c: { label: 'center c', min: -6, max: 6, step: 0.2, value: 0 },
      r: { label: 'radius r', min: 0, max: 8, step: 0.1, value: 3 },
      x: { label: 'x (drag to find the boundary)', min: -10, max: 10, step: 0.05, value: 0 },
    },
    variables: [
      { symbol: 'c', meaning: 'the center of the allowed interval' },
      { symbol: 'r', meaning: 'the allowed distance from the center' },
      { symbol: 'x', meaning: 'a test point' },
    ],
    explanation: {
      intuition: [
        'The curve is a V with its point at $x = c$, shifted down by $r$. Drag $x$ across the plot: everywhere the curve dips below the axis is exactly the set of $x$ satisfying $|x-c| < r$ — the two spots where it crosses zero are the boundary of that region.',
        'Widen $r$ and the V drops further, so the below-zero stretch widens on both sides at once — because distance from $c$ is being compared against a bigger radius. Move $c$ and the whole V, and hence the solution interval, just slides sideways with it.',
      ],
      formal: [
        '$|x - c| < r$ (for $r > 0$) means $x$ lies within $r$ of $c$: $c - r < x < c + r$.',
        'Equivalently, $|x-c| - r < 0$, so the solution set is exactly where the plotted function is negative.',
      ],
      advanced: ['The same reasoning with $>$ instead of $<$ gives the complementary set $x < c-r$ or $x > c+r$ — a union of two rays, not an interval — because the absolute value function is convex with a single minimum, so it is below any positive threshold on one connected interval but above it on two separate pieces.'],
    },
    derivation: [
      { tex: r`|x - c| < r`, note: 'Distance from $c$ to $x$ is less than $r$.' },
      { tex: r`-r < x - c < r`, note: 'Definition of absolute value as a two-sided bound.' },
      { tex: r`c - r < x < c + r`, note: 'Add $c$ to all three parts.' },
    ],
    realWorld: [
      { title: 'Manufacturing tolerances', text: 'A part is acceptable if its measurement is within $r$ of the target $c$ — precisely an absolute-value inequality.' },
      { title: 'Error bars and confidence', text: 'A measurement "accurate to within $r$" defines an interval exactly this way.' },
      { title: 'Signal thresholds', text: 'A control system flags a fault when a reading strays more than $r$ from its setpoint.' },
      { title: 'GPS and geofencing', text: 'Being "within range" of a location is an absolute-value (distance) condition in one or more dimensions.' },
    ],
  },
  {
    id: 'percent-and-compound-growth',
    title: 'Percent change and compound growth',
    subject: 'algebra',
    difficulty: 'high-school',
    equation: r`A(x) = P\left(1 + \frac{\text{rate}}{100}\right)^{x}`,
    summary: 'Applying the same percentage change repeatedly compounds — each period grows off the new, larger total, not the original one.',
    concepts: ['percent', 'compound-growth', 'exponential'],
    prerequisites: ['exponents-and-powers'],
    related: ['exponential-growth', 'logarithms'],
    visualization: { type: 'function-plot', options: { expr: 'P*(1 + rate/100)^x', domain: [0, 20], range: [-2, 30], mode: 'tangent' } },
    parameters: {
      P: { label: 'starting amount P', min: 1, max: 10, step: 0.5, value: 4 },
      rate: { label: 'rate per period (%)', min: -20, max: 25, step: 0.5, value: 8 },
      x: { label: 'number of periods', min: 0, max: 20, step: 0.05, value: 8 },
    },
    variables: [
      { symbol: 'P', meaning: 'starting amount' },
      { symbol: 'rate', meaning: 'percent change applied each period' },
      { symbol: 'x', meaning: 'number of periods elapsed' },
    ],
    explanation: {
      intuition: [
        'Drag $x$ forward one period at a time and watch the tangent line steepen: because each period\'s growth is a percentage of the current, already-grown total, the amount added per period keeps increasing — compounding is growth feeding on itself.',
        'Set the rate negative and the curve becomes decay: shrinking by the same percentage each period, the amount lost per period keeps shrinking too, so the curve falls fast at first and then flattens, never quite reaching zero — the same shape as radioactive decay.',
      ],
      formal: [
        'After $x$ periods, $A(x) = P(1 + \\text{rate}/100)^x$; the growth factor per period is constant, $(1+\\text{rate}/100)$, not the increment.',
        'For small rates and many compounding periods this approaches continuous exponential growth $Pe^{kx}$ with $k \\approx \\text{rate}/100$.',
      ],
      advanced: ['Compounding $m$ times a year at nominal annual rate $\\rho$ gives $(1 + \\rho/m)^{m}$ per year; as $m \\to \\infty$ this tends to $e^{\\rho}$ by the standard limit definition of $e$, which is exactly the bridge between compound growth here and the continuous exponential in the calculus lessons.'],
    },
    derivation: [
      { tex: r`A(1) = P + P\cdot\frac{\text{rate}}{100} = P\left(1+\frac{\text{rate}}{100}\right)`, note: 'One period multiplies by the growth factor.' },
      { tex: r`A(2) = A(1)\left(1+\frac{\text{rate}}{100}\right) = P\left(1+\frac{\text{rate}}{100}\right)^2`, note: 'Each period multiplies again by the same factor — not adding the same amount.' },
      { tex: r`A(x) = P\left(1+\frac{\text{rate}}{100}\right)^{x}`, note: 'After $x$ periods the factor has been applied $x$ times.' },
    ],
    realWorld: [
      { title: 'Savings and debt', text: 'Compound interest is exactly this formula, for good (savings) or ill (credit card debt).' },
      { title: 'Inflation', text: 'Prices rising a fixed percent per year compound, so purchasing power erodes faster than a straight-line estimate suggests.' },
      { title: 'Population and viral growth', text: 'A population growing a fixed percent per generation follows the same compounding law as money.' },
      { title: 'Depreciation', text: 'A car losing a fixed percent of its value each year is compound decay — rate negative.' },
    ],
  },
  // ---------- trigonometry ----------
  {
    id: 'sine-function-parameters',
    title: 'Amplitude, frequency, phase and shift',
    subject: 'trigonometry',
    difficulty: 'high-school',
    equation: r`f(x) = A\sin(\omega x + \varphi) + D`,
    summary: 'Four numbers fully describe any sinusoid: how tall it is, how fast it oscillates, where it starts, and where it sits vertically.',
    concepts: ['sine', 'amplitude', 'angular-frequency', 'phase-shift'],
    prerequisites: ['unit-circle', 'function-graph'],
    related: ['sine-wave', 'tangent-function'],
    visualization: { type: 'function-plot', options: { expr: 'A*sin(w*x + phi) + D', domain: [0, 12], range: [-6, 6], mode: 'tangent' } },
    parameters: {
      A: { label: 'amplitude A', min: 0.2, max: 4, step: 0.1, value: 2 },
      w: { label: 'angular frequency ω', min: 0.2, max: 3, step: 0.05, value: 1, unit: 'rad/unit' },
      phi: { label: 'phase φ', min: 0, max: 6.28, step: 0.05, value: 0, unit: 'rad' },
      D: { label: 'vertical shift D', min: -3, max: 3, step: 0.1, value: 0 },
      x: { label: 'x (drag along the curve)', min: 0, max: 12, step: 0.02, value: 3 },
    },
    variables: [
      { symbol: 'A', meaning: 'amplitude — how far above and below the midline it swings' },
      { symbol: r`\omega`, meaning: 'angular frequency — how quickly the argument advances' },
      { symbol: r`\varphi`, meaning: 'phase — shifts the whole pattern left or right' },
      { symbol: 'D', meaning: 'vertical shift — the midline the curve oscillates around' },
    ],
    explanation: {
      intuition: [
        'Increase $A$ and the whole curve stretches vertically without changing where it crosses its midline; increase $D$ and it slides straight up, midline and all — the two knobs affect height and position independently.',
        'Increase $\\omega$ and the peaks bunch closer together — the curve repeats faster because the same $2\\pi$ of angle is covered over a shorter stretch of $x$. Change $\\varphi$ and nothing about the shape changes at all, only where it starts: the whole curve just slides left or right.',
      ],
      formal: [
        'Period $T = 2\\pi/\\omega$; the curve oscillates between $D - A$ and $D + A$.',
        'The tangent slope at any $x$ is $A\\omega\\cos(\\omega x + \\varphi)$ — steepest at the midline crossings, zero at the peaks and troughs.',
      ],
      advanced: ['Any sinusoid $A\\sin(\\omega x + \\varphi)$ can be rewritten as $a\\sin(\\omega x) + b\\cos(\\omega x)$ with $a = A\\cos\\varphi$, $b = A\\sin\\varphi$ — the amplitude/phase form and the sum-of-sine-and-cosine form are the same two degrees of freedom, just in polar versus Cartesian coordinates.'],
    },
    derivation: [
      { tex: r`f(x) = A\sin(\omega x + \varphi) + D`, note: 'Start from the general form.' },
      { tex: r`f'(x) = A\omega\cos(\omega x + \varphi)`, note: 'Differentiate using the chain rule: derivative of the inner linear argument is $\\omega$.' },
      { tex: r`\max f = D + A, \quad \min f = D - A, \quad T = \frac{2\pi}{\omega}`, note: 'Extremes occur where $f\'=0$; the period follows from when the argument advances by $2\\pi$.' },
    ],
    realWorld: [
      { title: 'AC electricity', text: 'Mains voltage is $A\\sin(\\omega t + \\varphi)$; $\\omega$ sets 50/60 Hz and $\\varphi$ captures phase differences between circuits.' },
      { title: 'Tides', text: 'Sea level oscillates with an amplitude, a roughly 12-hour period, and a phase that depends on the coastline.' },
      { title: 'Audio synthesis', text: 'A musical tone is built from sinusoids whose amplitude sets loudness and frequency sets pitch.' },
      { title: 'Seasonal data', text: 'Average daily temperature over a year is well fit by a sine with a 12-month period and a vertical shift equal to the yearly mean.' },
    ],
  },
  {
    id: 'tangent-function',
    title: 'The tangent function and its asymptotes',
    subject: 'trigonometry',
    difficulty: 'high-school',
    equation: r`f(x) = \tan x = \frac{\sin x}{\cos x}`,
    summary: 'Tangent is a ratio that blows up wherever cosine is zero — the curve repeats every $\\pi$ and shoots to infinity at each end of every branch.',
    concepts: ['tangent', 'asymptote', 'periodicity'],
    prerequisites: ['unit-circle', 'sine-function-parameters'],
    related: ['sine-function-parameters', 'one-sided-and-infinite-limits'],
    visualization: { type: 'function-plot', options: { expr: 'tan(x)', domain: [-6, 6], range: [-6, 6], mode: 'plain' } },
    parameters: {
      x: { label: 'x', min: -6, max: 6, step: 0.01, value: 0.5 },
    },
    variables: [
      { symbol: 'x', meaning: 'angle in radians' },
      { symbol: r`\tan x`, meaning: r`\sin x / \cos x` },
    ],
    explanation: {
      intuition: [
        'Drag the point slowly toward $x = \\pi/2 \\approx 1.57$: the curve rockets upward, because $\\cos x$ is heading to zero in the denominator while $\\sin x$ stays near one. Just past that point the curve reappears from far below — same formula, opposite sign of $\\cos x$.',
        'Keep dragging and the whole pattern repeats every $\\pi$ units, half the period of sine or cosine alone, because tangent only cares about the ratio, which returns to itself twice as often as sine and cosine individually do.',
      ],
      formal: [
        '$\\tan x$ is undefined wherever $\\cos x = 0$, i.e. at $x = \\pi/2 + n\\pi$ for integer $n$; these are vertical asymptotes.',
        'Period $\\pi$: $\\tan(x + \\pi) = \\tan x$ for all $x$ in the domain.',
      ],
      advanced: ['Near each asymptote $\\tan x$ has opposite one-sided limits — $+\\infty$ approaching $\\pi/2$ from the left, $-\\infty$ from the right — so the function has an essential discontinuity there rather than a removable one; this is why "the limit at $\\pi/2$" does not exist even though both one-sided limits are infinite.'],
    },
    derivation: [
      { tex: r`\tan x = \frac{\sin x}{\cos x}`, note: 'Definition as a ratio of sine and cosine.' },
      { tex: r`\cos x = 0 \;\Rightarrow\; x = \tfrac{\pi}{2} + n\pi`, note: 'The denominator vanishes at these points, producing vertical asymptotes.' },
      { tex: r`\tan(x+\pi) = \frac{\sin(x+\pi)}{\cos(x+\pi)} = \frac{-\sin x}{-\cos x} = \tan x`, note: 'Both sine and cosine flip sign after $\\pi$, so their ratio does not — period $\\pi$.' },
    ],
    realWorld: [
      { title: 'Slopes and angles', text: 'The tangent of an incline angle is literally its slope — rise over run.' },
      { title: 'Surveying and navigation', text: 'Heights and distances are recovered from measured angles via the tangent function.' },
      { title: 'Optics', text: 'The tangent of the angle of incidence appears in lens and prism calculations.' },
      { title: 'Camera field of view', text: 'A camera\'s horizontal coverage at distance $d$ is $2d\\tan(\\theta/2)$ for field-of-view angle $\\theta$.' },
    ],
  },
  // ---------- calculus ----------
  {
    id: 'one-sided-and-infinite-limits',
    title: 'One-sided and infinite limits',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`\lim_{x\to 0^-}\frac1x = -\infty, \qquad \lim_{x\to 0^+}\frac1x = +\infty`,
    summary: 'Approach $x=0$ from the left and right on $y=1/x$ and you head to two different infinities — the two-sided limit does not exist.',
    concepts: ['limit', 'one-sided-limit', 'vertical-asymptote'],
    prerequisites: ['limit', 'function-graph'],
    related: ['limit', 'tangent-function', 'limits-at-infinity'],
    visualization: { type: 'function-plot', options: { expr: '1/x', domain: [-4, 4], range: [-10, 10], mode: 'limit', limitAt: 0 } },
    parameters: {
      d: { label: 'distance from x = 0', min: 0.02, max: 3, step: 0.01, value: 1 },
    },
    variables: [
      { symbol: 'd', meaning: 'distance of the two approaching points from $x=0$' },
      { symbol: r`\lim_{x\to0^-}`, meaning: 'limit approaching from the left' },
      { symbol: r`\lim_{x\to0^+}`, meaning: 'limit approaching from the right' },
    ],
    explanation: {
      intuition: [
        'Shrink $d$ and watch both dots close in on $x = 0$ from opposite sides. The table of values makes it concrete: from the right, $1/x$ grows without bound toward $+\\infty$; from the left, it plunges toward $-\\infty$. They are not converging on the same number — they are diverging in opposite directions.',
        'This is exactly what the vertical line at $x=0$ on the graph is telling you: the curve never settles near any finite height there. Whenever the two one-sided behaviors disagree like this, mathematicians say the limit simply does not exist, even though each side individually has a clear (infinite) trend.',
      ],
      formal: [
        '$\\lim_{x\\to 0^+} \\frac1x = +\\infty$ and $\\lim_{x\\to 0^-}\\frac1x = -\\infty$; since these one-sided limits disagree, $\\lim_{x\\to0}\\frac1x$ does not exist (not even as an infinite limit).',
        'A vertical asymptote at $x=c$ means at least one of the one-sided limits there is $+\\infty$ or $-\\infty$.',
      ],
      advanced: ['"Infinite limit" is a convenient abuse of the word limit: $\\infty$ is not a real number, so these statements are really shorthand for "for every $M$ there is a $\\delta$ such that $0 < x < \\delta$ implies $1/x > M$" — the function is eventually larger than any bound, not that it converges to some value called infinity.'],
    },
    derivation: [
      { tex: r`0 < x < \delta \;\Rightarrow\; \frac1x > \frac1\delta`, note: 'As $x$ shrinks toward $0$ from the right, $1/x$ grows without bound.' },
      { tex: r`\forall M > 0,\ \exists\, \delta = 1/M \text{ s.t. } 0<x<\delta \Rightarrow \tfrac1x > M`, note: 'This is precisely the $\\varepsilon$–$\\delta$-style definition of an infinite limit.' },
      { tex: r`-\delta < x < 0 \;\Rightarrow\; \frac1x < -\frac1\delta`, note: 'From the left, the same argument gives $1/x \\to -\\infty$ — the opposite sign.' },
    ],
    realWorld: [
      { title: 'Electric field near a point charge', text: 'Field strength scales like $1/r^2$ and diverges as you approach the charge — a physical vertical asymptote.' },
      { title: 'Lens focal blur', text: 'Magnification formulas in optics blow up as an object approaches the focal distance.' },
      { title: 'Resource allocation', text: 'Cost-per-unit of a fixed cost spread over $x$ units, $C/x$, diverges as $x\\to 0$ — spreading a fixed cost over almost nothing is unboundedly expensive.' },
      { title: 'Control systems', text: 'A transfer function\'s poles are exactly the points where its output has this kind of infinite, sign-flipping limit, marking instability.' },
    ],
  },
  {
    id: 'limits-at-infinity',
    title: 'Limits at infinity and horizontal asymptotes',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`\lim_{x\to\infty}\frac{ax^2+1}{x^2+b} = a`,
    summary: 'For large $x$, only the highest powers matter — the lower-order terms fade into insignificance and the ratio settles onto a flat horizontal line.',
    concepts: ['limit-at-infinity', 'horizontal-asymptote', 'rational-function'],
    prerequisites: ['limit', 'function-graph'],
    related: ['one-sided-and-infinite-limits', 'limit'],
    visualization: { type: 'function-plot', options: { expr: '(a*x^2 + 1)/(x^2 + b)', domain: [0, 60], range: [-1, 5], mode: 'plain' } },
    parameters: {
      a: { label: 'a (limiting height)', min: 0.5, max: 4, step: 0.1, value: 2 },
      b: { label: 'b', min: 0.5, max: 8, step: 0.1, value: 3 },
      x: { label: 'x (drag far to the right)', min: 0, max: 60, step: 0.1, value: 5 },
    },
    variables: [
      { symbol: 'a', meaning: 'coefficient of the leading term — becomes the asymptote height' },
      { symbol: 'b', meaning: 'constant added to the denominator\'s leading term' },
      { symbol: 'x', meaning: 'input, dragged out toward large values' },
    ],
    explanation: {
      intuition: [
        'Drag $x$ out past $x = 30$ or $40$: the curve, however it wiggled near the origin, has flattened out and is hugging a horizontal line. Read off its height and compare to the slider for $a$ — they match, however $b$ is set.',
        'Change $b$ and watch closely: it visibly reshapes the curve near $x = 0$, where the $+1$ and $+b$ terms are comparable in size to $x^2$, but has no effect at all on the flat height far to the right, because out there $x^2$ dwarfs both constants — only the ratio of leading coefficients, $a/1$, survives.',
      ],
      formal: [
        '$\\lim_{x\\to\\infty}\\frac{ax^2+1}{x^2+b} = a$, since dividing numerator and denominator by $x^2$ sends the constant terms to $0$.',
        'The line $y=a$ is a horizontal asymptote: the graph approaches it as $x\\to\\infty$ but need not ever equal it.',
      ],
      advanced: ['This is a special case of the general rule for rational functions $p(x)/q(x)$: if $\\deg p = \\deg q$, the limit at infinity is the ratio of leading coefficients; if $\\deg p < \\deg q$ it is $0$; if $\\deg p > \\deg q$ there is no finite limit (the function diverges, possibly along a slant asymptote).'],
    },
    derivation: [
      { tex: r`\frac{ax^2+1}{x^2+b} = \frac{a + 1/x^2}{1 + b/x^2}`, note: 'Divide every term by $x^2$, the highest power present.' },
      { tex: r`\lim_{x\to\infty}\frac{1}{x^2} = 0, \qquad \lim_{x\to\infty}\frac{b}{x^2} = 0`, note: 'Any constant divided by a growing $x^2$ vanishes in the limit.' },
      { tex: r`\lim_{x\to\infty}\frac{a+1/x^2}{1+b/x^2} = \frac{a+0}{1+0} = a`, note: 'Substitute the vanished terms — only the leading coefficients survive.' },
    ],
    realWorld: [
      { title: 'Terminal velocity', text: 'Drag models like $v(t) \\to v_{\\text{terminal}}$ as $t\\to\\infty$ are horizontal-asymptote limits.' },
      { title: 'Michaelis–Menten enzyme kinetics', text: 'Reaction rate approaches a maximum $V_{\\max}$ as substrate concentration grows — a rational-function asymptote.' },
      { title: 'Long-run cost averages', text: 'Average cost per unit as production scales up settles toward the marginal cost, the horizontal asymptote of a cost-ratio curve.' },
      { title: 'Signal-to-noise saturation', text: 'Many detector responses saturate toward a fixed level as input intensity grows without bound.' },
    ],
  },
  {
    id: 'continuity',
    title: 'Continuity and jump discontinuities',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`f \text{ continuous at } c \;\Longleftrightarrow\; \lim_{x\to c^-} f(x) = \lim_{x\to c^+} f(x) = f(c)`,
    summary: 'A function is continuous where its graph can be drawn without lifting the pen — where the limit from both sides agrees with the value there.',
    concepts: ['continuity', 'limit', 'piecewise-function'],
    prerequisites: ['limit', 'one-sided-and-infinite-limits'],
    related: ['one-sided-and-infinite-limits', 'limit'],
    visualization: { type: 'function-plot', options: { expr: 'x < 1 ? x^2 : x^2 + j', domain: [-2, 4], range: [-1, 7], mode: 'limit', limitAt: 1 } },
    parameters: {
      d: { label: 'distance from x = 1', min: 0.02, max: 1.5, step: 0.01, value: 0.5 },
      j: { label: 'jump size j', min: -3, max: 3, step: 0.1, value: 1.5 },
    },
    variables: [
      { symbol: 'j', meaning: 'the size of the jump added for $x \\ge 1$' },
      { symbol: 'd', meaning: 'distance of the two approaching points from $x=1$' },
    ],
    explanation: {
      intuition: [
        'With $j$ away from zero, shrink $d$ and watch the two approaching dots: the one coming from the left settles near $1$ (since $1^2 = 1$), while the one from the right settles near $1 + j$. They are closing in on two different heights, so no single limit exists at $x=1$, and the graph visibly has a step in it there.',
        'Now drag $j$ down to exactly $0$: the two branches — $x^2$ below $1$ and $x^2 + j$ above — meet perfectly, the step disappears, and both one-sided limits agree with each other and with $f(1)$. That is continuity: the algebraic condition and the "no pen lift" picture are the same fact.',
      ],
      formal: [
        '$f$ is continuous at $c$ iff $\\lim_{x\\to c^-}f(x) = \\lim_{x\\to c^+}f(x) = f(c)$.',
        'Here $f(1) = 1 + j$ (using the right branch\'s definition at the boundary), $\\lim_{x\\to1^-}f = 1$, $\\lim_{x\\to1^+}f = 1+j$; continuity requires $j = 0$.',
      ],
      advanced: ['This is a jump discontinuity (both one-sided limits exist but disagree), distinct from a removable discontinuity (limits agree but differ from $f(c)$, or $f(c)$ is undefined) and from the essential/infinite discontinuities seen with $1/x$ or $\\tan x$ — the three types cover every way a function can fail to be continuous at a point.'],
    },
    derivation: [
      { tex: r`\lim_{x\to1^-} x^2 = 1`, note: 'Approaching from the left uses the branch $x^2$.' },
      { tex: r`\lim_{x\to1^+} (x^2+j) = 1+j`, note: 'Approaching from the right uses the other branch.' },
      { tex: r`1 = 1+j \;\Longleftrightarrow\; j = 0`, note: 'Continuity needs the two one-sided limits to agree — forces $j=0$.' },
    ],
    realWorld: [
      { title: 'Tax brackets', text: 'A poorly designed tax schedule can jump discontinuously at a bracket boundary, so earning one more dollar costs you far more than a dollar in tax.' },
      { title: 'Structural loads', text: 'Sudden material changes in a beam can create discontinuous stress profiles that engineers must smooth or account for.' },
      { title: 'Digital signal quantization', text: 'Rounding a continuous signal to discrete levels introduces jump discontinuities at the rounding boundaries.' },
      { title: 'Phase transitions', text: 'Some physical quantities (like density at a phase change) jump discontinuously as temperature crosses a threshold.' },
    ],
  },
  {
    id: 'chain-and-product-rule',
    title: 'The chain rule and product rule together',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`\frac{d}{dx}\big[\sin(kx)\cdot x\big] = kx\cos(kx) + \sin(kx)`,
    summary: 'Differentiating a product of two functions, one of which is itself a composition, needs the product rule and the chain rule working together.',
    concepts: ['chain-rule', 'product-rule', 'derivative'],
    prerequisites: ['derivative', 'sine-function-parameters'],
    related: ['derivative', 'sine-function-parameters'],
    visualization: { type: 'function-plot', options: { expr: 'sin(k*x)*x', domain: [-6, 6], range: [-8, 8], mode: 'tangent', showDerivative: true } },
    parameters: {
      k: { label: 'k (inner frequency)', min: 0.3, max: 3, step: 0.05, value: 1 },
      x: { label: 'x (drag along the curve)', min: -6, max: 6, step: 0.02, value: 2 },
    },
    variables: [
      { symbol: 'k', meaning: 'frequency inside the sine — the "inner function" being composed' },
      { symbol: 'x', meaning: 'point where the tangent and derivative are evaluated' },
    ],
    explanation: {
      intuition: [
        'Drag the point and compare the solid tangent line\'s slope with the dashed derivative curve beneath it — they always agree by construction. Notice the derivative curve is not just a shifted sine: near the origin it is dominated by the flat $\\sin(kx)$ term, but for large $|x|$ the $kx\\cos(kx)$ term wins and the derivative swings with growing amplitude.',
        'Increase $k$ and watch both curves oscillate faster — but also notice the derivative\'s amplitude grows too, not just its frequency. That is the chain rule\'s fingerprint: differentiating $\\sin(kx)$ brings down an extra factor of $k$, so a faster inner oscillation always produces a steeper, wilder derivative.',
      ],
      formal: [
        'Product rule: $(uv)\' = u\'v + uv\'$ with $u = \\sin(kx)$, $v = x$.',
        'Chain rule: $\\dfrac{d}{dx}\\sin(kx) = k\\cos(kx)$, since the derivative of the outer sine is evaluated at the inner function, times the inner function\'s own derivative $k$.',
      ],
      advanced: ['This derivative, $kx\\cos(kx) + \\sin(kx)$, is exactly the pattern that shows up differentiating $\\int \\sin(kt)\\,dt$-type expressions or analysing amplitude-modulated signals $x(t)\\sin(kt)$: the product rule splits the change into a part from the (slowly varying) envelope and a part from the (fast) oscillation, which is the starting point for the general Leibniz rule and for stationary-phase approximations.'],
    },
    derivation: [
      { tex: r`\frac{d}{dx}\big[\sin(kx)\cdot x\big] = \frac{d}{dx}\big[\sin(kx)\big]\cdot x + \sin(kx)\cdot \frac{d}{dx}[x]`, note: 'Apply the product rule to the two factors $\\sin(kx)$ and $x$.' },
      { tex: r`\frac{d}{dx}\sin(kx) = \cos(kx)\cdot k`, note: 'Apply the chain rule to the composed inner function $kx$.' },
      { tex: r`= kx\cos(kx) + \sin(kx)`, note: 'Combine: $\\frac{d}{dx}[x] = 1$, and substitute the chain-rule result.' },
    ],
    realWorld: [
      { title: 'Amplitude-modulated radio', text: 'A carrier wave multiplied by a slowly varying envelope needs exactly this product-and-chain differentiation to analyse.' },
      { title: 'Vibration with growing drive', text: 'A driven oscillator whose forcing amplitude ramps up linearly while oscillating shows this same $x\\sin(kx)$ shape.' },
      { title: 'Optimization in engineering', text: 'Composite cost functions (a rate applied to a changing quantity) routinely require chaining derivatives through several layers.' },
      { title: 'Machine learning backpropagation', text: 'Gradients through neural network layers are chain rule applied repeatedly, often combined with products at each layer.' },
    ],
  },
  {
    id: 'fundamental-theorem',
    title: 'The fundamental theorem of calculus',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`\frac{d}{dx}\int_a^x f(t)\,dt = f(x)`,
    summary: 'Differentiation and integration are inverse operations: the area accumulated so far, differentiated, gives back the very curve you were finding area under.',
    concepts: ['fundamental-theorem-of-calculus', 'integral', 'derivative', 'accumulation'],
    prerequisites: ['integral', 'derivative', 'area-under-curve'],
    related: ['integral', 'area-under-curve', 'derivative'],
    visualization: { type: 'function-plot', options: { expr: '2*sin(x) + 0.5', domain: [0, 10], range: [-2, 3], mode: 'area' } },
    charts: [{ title: 'Accumulated distance F(b) = ∫ from 0 to b', xLabel: 'b', yLabel: 'F(b)', domain: [0, 10], marker: 'b', series: [{ label: 'F(b) = -2cos(x) + 0.5x + 2', expr: '-2*cos(x) + 0.5*x + 2' }] }],
    parameters: {
      a: { label: 'a (start)', min: 0, max: 9, step: 0.1, value: 0 },
      b: { label: 'b (end)', min: 0, max: 10, step: 0.1, value: 4 },
    },
    variables: [
      { symbol: 'v(x)', meaning: 'the curve being shaded — think of it as a velocity' },
      { symbol: 'F(b)', meaning: 'accumulated area (distance) from $a=0$ up to $b$ — the chart below' },
      { symbol: 'a, b', meaning: 'the bounds of the shaded region' },
    ],
    explanation: {
      intuition: [
        'Drag $b$ to the right with $a$ fixed at $0$ and watch two things at once: the shaded area above grows or shrinks, and the chart\'s marker on $F(b)$ moves to match — the chart is literally tracking the running total of the shaded area as $b$ advances.',
        'Now look at where $v(x) = 2\\sin(x) + 0.5$ is positive versus negative: exactly where it is positive, $F(b)$ in the chart is climbing; exactly where $v(x)$ dips negative, $F(b)$ turns around and falls. The curve above is the slope of the chart below — differentiating the accumulated area gives back the very curve you integrated.',
      ],
      formal: [
        'If $F(b) = \\int_a^b f(x)\\,dx$, then $F\'(b) = f(b)$ — the Fundamental Theorem of Calculus, Part 1.',
        'Part 2: if $F$ is any antiderivative of $f$, then $\\int_a^b f(x)\\,dx = F(b) - F(a)$, turning area computation into evaluating an antiderivative at two points.',
      ],
      advanced: ['The proof of Part 1 hinges on the Mean Value Theorem for integrals: $F(b+h)-F(b) = \\int_b^{b+h} f \\approx f(b)\\,h$ for small $h$ because $f$ is continuous, so the difference quotient $[F(b+h)-F(b)]/h \\to f(b)$ — accumulation and instantaneous rate are two sides of the same limiting process, one taken over an interval, one at a point.'],
    },
    derivation: [
      { tex: r`F(b) = \int_a^b f(x)\,dx`, note: 'Define the accumulated area up to $b$.' },
      { tex: r`F(b+h) - F(b) = \int_b^{b+h} f(x)\,dx \approx f(b)\,h`, note: 'The extra sliver of area is approximately a thin rectangle of height $f(b)$ and width $h$, for small $h$.' },
      { tex: r`F'(b) = \lim_{h\to0}\frac{F(b+h)-F(b)}{h} = f(b)`, note: 'Divide by $h$ and take the limit: the derivative of the accumulated area is the curve itself.' },
    ],
    realWorld: [
      { title: 'Velocity and distance', text: 'A car\'s odometer reading is the accumulated area under its velocity-time graph; its speedometer is the derivative of the odometer reading.' },
      { title: 'Water tank filling', text: 'Total water in a tank is the accumulated inflow rate; the inflow rate is the derivative of the total.' },
      { title: 'Economics', text: 'Total cost is the accumulated marginal cost; marginal cost is the derivative of total cost.' },
      { title: 'Physics work-energy', text: 'Work done is the area under a force-displacement curve; force is the derivative (rate of change) of accumulated work with displacement.' },
    ],
  },
  {
    id: 'improper-integrals',
    title: 'Improper integrals and p-series convergence',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`\int_1^\infty \frac{dx}{x^p} \text{ converges} \iff p > 1`,
    summary: 'Stretching the upper limit of integration toward infinity, whether the accumulated area settles down or grows forever depends entirely on how fast the curve decays.',
    concepts: ['improper-integral', 'convergence', 'integral'],
    prerequisites: ['integral', 'area-under-curve', 'limits-at-infinity'],
    related: ['limits-at-infinity', 'integral', 'fundamental-theorem'],
    visualization: { type: 'function-plot', options: { expr: '1/x^p', domain: [1, 60], range: [0, 3], mode: 'area' } },
    parameters: {
      p: { label: 'exponent p', min: 0.2, max: 3, step: 0.05, value: 0.8 },
      a: { label: 'a (start, fixed near 1)', min: 1, max: 3, step: 0.1, value: 1 },
      b: { label: 'b (push far to the right)', min: 1, max: 60, step: 0.5, value: 10 },
    },
    variables: [
      { symbol: 'p', meaning: 'the power in the decaying curve $1/x^p$' },
      { symbol: 'a, b', meaning: 'the bounds of the shaded, finite-$b$ approximation' },
    ],
    explanation: {
      intuition: [
        'Set $p$ below $1$ (say $0.5$) and drag $b$ out to $60$: the shaded area keeps growing noticeably even out at large $b$ — the curve is not shrinking fast enough for the accumulating strip of area to level off. Every time you push $b$ further, you pick up a meaningful new chunk.',
        'Now push $p$ above $1$ (say $2$) and drag $b$ out again: past a certain point, pushing $b$ further barely changes the shaded area at all — the tail of the curve has become so thin that its remaining contribution is negligible. That visual "stops growing" is exactly what convergence of the improper integral looks like.',
      ],
      formal: [
        '$\\int_1^\\infty x^{-p}\\,dx = \\lim_{b\\to\\infty}\\int_1^b x^{-p}\\,dx$; this limit is finite iff $p>1$, in which case it equals $\\frac{1}{p-1}$.',
        'For $p \\le 1$ the integral diverges: at $p=1$ it grows like $\\ln b \\to \\infty$; for $p<1$ it grows like $b^{1-p} \\to \\infty$.',
      ],
      advanced: ['This is the integral test for series: $\\sum n^{-p}$ converges iff $p>1$ for exactly the same reason, since a decreasing positive $f(x)=x^{-p}$ has $\\sum_{n\\ge1} f(n)$ sandwiched between $\\int_1^\\infty f$ and $f(1)+\\int_1^\\infty f$ — the improper integral and the infinite series diverge or converge together.'],
    },
    derivation: [
      { tex: r`\int_1^b x^{-p}\,dx = \left[\frac{x^{1-p}}{1-p}\right]_1^b = \frac{b^{1-p}-1}{1-p} \quad (p\ne1)`, note: 'Ordinary power-rule antiderivative, evaluated at the bounds.' },
      { tex: r`p>1 \;\Rightarrow\; 1-p<0 \;\Rightarrow\; \lim_{b\to\infty} b^{1-p} = 0`, note: 'A negative exponent on a growing $b$ sends that term to zero.' },
      { tex: r`\lim_{b\to\infty}\int_1^b x^{-p}\,dx = \frac{0-1}{1-p} = \frac{1}{p-1}`, note: 'Substitute the vanished term — the improper integral converges to a finite value.' },
    ],
    realWorld: [
      { title: 'Gravity and escape velocity', text: 'The work to escape a gravitational field is an improper integral of $1/r^2$ from a planet\'s surface to infinity — it converges because $p=2>1$.' },
      { title: 'Probability distributions', text: 'A probability density must integrate to a finite total (1) over an infinite domain — heavy-tailed distributions sit right at this convergence boundary.' },
      { title: 'Signal energy', text: 'Total energy in a signal is an integral of its squared amplitude over infinite time; whether it is finite determines if a signal is "energy-limited".' },
      { title: 'Radiative heat loss', text: 'Some cooling and radiation models involve integrals over unbounded domains whose convergence determines whether total heat lost is finite.' },
    ],
  },
  {
    id: 'logistic-growth',
    title: 'Logistic growth and carrying capacity',
    subject: 'calculus',
    difficulty: 'university',
    equation: r`\frac{dy}{dt} = ky\left(1-\frac{y}{K}\right) \;\Longrightarrow\; y = \frac{K}{1+\left(\frac{K-y_0}{y_0}\right)e^{-kt}}`,
    summary: 'Growth that starts exponential but slows as it nears a ceiling $K$ traces an S-shaped curve — fast in the middle, flat at both ends.',
    concepts: ['logistic-equation', 'carrying-capacity', 'differential-equation'],
    prerequisites: ['exponential-growth', 'derivative'],
    related: ['exponential-growth', 'derivative'],
    visualization: { type: 'function-plot', options: { expr: 'K/(1 + ((K - y0)/y0)*exp(-k*x))', domain: [0, 20], range: [0, 12], mode: 'tangent' } },
    parameters: {
      K: { label: 'carrying capacity K', min: 2, max: 10, step: 0.5, value: 8 },
      y0: { label: 'starting amount y₀', min: 0.1, max: 3, step: 0.05, value: 0.5 },
      k: { label: 'growth rate k', min: 0.1, max: 1.5, step: 0.05, value: 0.6 },
      x: { label: 'time t', min: 0, max: 20, step: 0.02, value: 6 },
    },
    variables: [
      { symbol: 'K', meaning: 'carrying capacity — the ceiling the curve approaches' },
      { symbol: 'y_0', meaning: 'starting amount at $t=0$' },
      { symbol: 'k', meaning: 'intrinsic growth rate' },
    ],
    explanation: {
      intuition: [
        'Drag the point through the early part of the curve, where $y$ is small compared to $K$: the tangent slope grows steeply, almost like plain exponential growth, because the braking term $(1-y/K)$ is still close to $1$ and barely holding anything back.',
        'Keep dragging toward $K$: the tangent flattens out even though $y$ is at its largest, because now $(1-y/K)$ is shrinking toward zero and throttling the growth rate — the population is running out of room, resources or capacity, and the curve gently levels off just short of the ceiling.',
      ],
      formal: [
        'The governing ODE is $\\dot y = ky(1-y/K)$: growth proportional to $y$ (like exponential growth) but damped by a factor that vanishes as $y \\to K$.',
        'The solution is the logistic function $y(t) = K/\\big(1+\\big(\\tfrac{K-y_0}{y_0}\\big)e^{-kt}\\big)$, symmetric S-shape with inflection at $y=K/2$.',
      ],
      advanced: ['The inflection point, where growth rate itself is maximal, occurs exactly at $y=K/2$: differentiating $\\dot y = ky(1-y/K)$ with respect to $y$ and setting it to zero gives $y=K/2$, independent of $k$ or $y_0$ — the steepest part of every logistic curve, whatever its parameters, is always at the halfway point to capacity.'],
    },
    derivation: [
      { tex: r`\frac{dy}{y(1-y/K)} = k\,dt`, note: 'Separate variables in the logistic ODE.' },
      { tex: r`\int\left(\frac1y + \frac{1/K}{1-y/K}\right)dy = kt + C`, note: 'Partial fractions split the left side into two elementary integrals.' },
      { tex: r`y = \frac{K}{1+\left(\frac{K-y_0}{y_0}\right)e^{-kt}}`, note: 'Integrate, exponentiate, and fix the constant using $y(0)=y_0$.' },
    ],
    realWorld: [
      { title: 'Population ecology', text: 'Animal populations grow exponentially while resources are abundant, then level off near the environment\'s carrying capacity.' },
      { title: 'Epidemics', text: 'The S-curve of total infections in a simple epidemic model flattens as the pool of susceptible people is used up.' },
      { title: 'Product adoption', text: 'New technology adoption often follows a logistic S-curve: slow start, rapid middle growth, saturating market.' },
      { title: 'Tumor growth models', text: 'Some tumor growth is modeled logistically, with $K$ representing a resource- or space-limited maximum size.' },
    ],
  },
  {
    id: 'partial-derivatives-saddle',
    title: 'Partial derivatives and saddle points',
    subject: 'calculus',
    difficulty: 'advanced',
    equation: r`f(x,y) = x^2 - y^2, \qquad \nabla f = (2x,\, -2y)`,
    summary: 'A saddle curves upward in one direction and downward in the perpendicular direction at once — neither a hilltop nor a valley floor.',
    concepts: ['partial-derivative', 'saddle-point', 'gradient', 'multivariable'],
    prerequisites: ['gradient', 'derivative'],
    related: ['gradient'],
    visualization: { type: 'surface-3d', options: { expr: 'x^2 - y^2', extent: 2, zRange: [-4, 4] } },
    parameters: {
      x0: { label: 'point x', min: -2, max: 2, step: 0.01, value: 0.8 },
      y0: { label: 'point y', min: -2, max: 2, step: 0.01, value: 0 },
    },
    variables: [
      { symbol: r`\partial f/\partial x`, meaning: 'slope walking in the $x$ direction — here $2x$, always concave up' },
      { symbol: r`\partial f/\partial y`, meaning: 'slope walking in the $y$ direction — here $-2y$, always concave down' },
      { symbol: r`\nabla f`, meaning: 'the gradient — zero exactly at the saddle point' },
    ],
    explanation: {
      intuition: [
        'Move the point along the $x$-axis, keeping $y_0 = 0$: the tangent plane tilts like the wall of a valley, curving upward the way a bowl does. Now move along the $y$-axis instead, keeping $x_0=0$: the same surface curves downward like a hilltop. One surface, two completely opposite behaviors depending on which direction you walk.',
        'Bring the point back to the origin: the tangent plane goes perfectly flat and the gradient arrow shrinks to nothing, just as it would at a true minimum or maximum — but this flat point is neither. It is a saddle, the point a horse rider sits on: curving up toward the horse\'s head and tail, down toward its sides.',
      ],
      formal: [
        '$f_x = 2x$, $f_y = -2y$; both vanish only at the origin, so $(0,0)$ is the only critical point.',
        'The Hessian is $\\begin{pmatrix}2&0\\\\0&-2\\end{pmatrix}$, with eigenvalues of opposite sign — the signature of a saddle point, neither a local max nor min.',
      ],
      advanced: ['The second-derivative test formalises the picture: with $D = f_{xx}f_{yy} - f_{xy}^2$, $D<0$ at a critical point guarantees a saddle regardless of direction chosen, because the quadratic form $f_{xx}h^2 + 2f_{xy}hk + f_{yy}k^2$ (the local approximation of $f$ near the point) takes both signs — here $2h^2 - 2k^2$, positive along $h$, negative along $k$.'],
    },
    derivation: [
      { tex: r`f_x = \frac{\partial}{\partial x}(x^2-y^2) = 2x, \qquad f_y = \frac{\partial}{\partial y}(x^2-y^2) = -2y`, note: 'Differentiate holding the other variable fixed, one at a time.' },
      { tex: r`f_x = f_y = 0 \;\Longleftrightarrow\; x=0,\ y=0`, note: 'Critical points are where the gradient vanishes.' },
      { tex: r`H = \begin{pmatrix}f_{xx}&f_{xy}\\f_{xy}&f_{yy}\end{pmatrix} = \begin{pmatrix}2&0\\0&-2\end{pmatrix}`, note: 'The Hessian\'s mixed-sign eigenvalues classify the origin as a saddle, not an extremum.' },
    ],
    realWorld: [
      { title: 'Mountain passes', text: 'A literal mountain pass is a saddle point: lowest along the ridge, highest along the trail crossing it.' },
      { title: 'Game theory equilibria', text: 'A minimax equilibrium in a zero-sum game is a saddle point of the payoff function — best response in one direction, worst in the other.' },
      { title: 'Optimization pitfalls', text: 'Gradient descent can stall near saddle points in high-dimensional loss surfaces, since the gradient nearly vanishes without being at a true minimum.' },
      { title: 'Structural engineering', text: 'Saddle-shaped (hyperbolic paraboloid) roofs are strong precisely because they curve oppositely in two directions, resisting buckling both ways.' },
    ],
  },
]
