import type { Lesson } from './types'

const r = String.raw

/** Physics and waves lessons — pure data on top of function-plot / surface-3d. */
export const mechanics: Lesson[] = [
  // ---------- physics ----------
  {
    id: 'kinematics-constant-acceleration',
    title: 'Position, velocity and constant acceleration',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`x(t) = x_0 + v_0 t + \tfrac12 a t^2`,
    summary: 'Position under constant acceleration is a parabola in time; its slope at any instant is the velocity.',
    concepts: ['kinematics', 'velocity', 'acceleration', 'derivative'],
    prerequisites: ['newtons-second-law', 'derivative'],
    related: ['velocity-time-area', 'projectile-motion'],
    visualization: { type: 'function-plot', options: { expr: 'x0 + v0*x + 0.5*a*x^2', domain: [0, 10], range: [-10, 60], mode: 'tangent', showDerivative: true } },
    parameters: {
      x0: { label: 'starting position x₀', min: -5, max: 10, step: 0.5, value: 0, unit: 'm' },
      v0: { label: 'initial velocity v₀', min: -8, max: 8, step: 0.5, value: 2, unit: 'm/s' },
      a: { label: 'acceleration a', min: -4, max: 4, step: 0.2, value: 1, unit: 'm/s²' },
      x: { label: 'time t', min: 0, max: 10, step: 0.02, value: 4, unit: 's' },
    },
    variables: [
      { symbol: 'x_0', meaning: 'position at $t=0$' },
      { symbol: 'v_0', meaning: 'velocity at $t=0$' },
      { symbol: 'a', meaning: 'constant acceleration' },
      { symbol: 't', meaning: 'time (the horizontal axis, labelled $x$ on the plot)' },
    ],
    explanation: {
      intuition: [
        'Drag the point along the curve and watch the tangent line: its slope is the velocity at that instant, and the dashed derivative curve traces exactly that slope over time — a straight line, because velocity under constant acceleration changes at a steady rate.',
        'Set $a = 0$: the parabola straightens into a plain sloped line and the derivative curve goes flat — constant velocity, no acceleration. Now make $a$ negative with a positive $v_0$: the tangent starts steep and positive, flattens to zero at the peak, then tilts negative — the object slows, stops, and reverses, exactly like a ball thrown straight up.',
      ],
      formal: [
        '$x(t) = x_0 + v_0 t + \\tfrac12 a t^2$; differentiating gives $v(t) = x\'(t) = v_0 + at$.',
        'Differentiating again, $a(t) = v\'(t) = a$ — constant, consistent with the assumption.',
      ],
      advanced: ['This is the unique solution of $\\ddot x = a$ (a constant) with initial conditions $x(0)=x_0$, $\\dot x(0)=v_0$; it is the simplest second-order linear ODE with constant coefficients, and every higher kinematic quantity (jerk, snap) is defined by continuing to differentiate, each derivative flattening the previous curve\'s time-dependence by one degree.'],
    },
    derivation: [
      { tex: r`a(t) = a \;\text{(const.)}`, note: 'Start from constant acceleration.' },
      { tex: r`v(t) = \int_0^t a\,d\tau + v_0 = v_0 + at`, note: 'Integrate acceleration to get velocity, using $v(0)=v_0$.' },
      { tex: r`x(t) = \int_0^t v(\tau)\,d\tau + x_0 = x_0 + v_0 t + \tfrac12 a t^2`, note: 'Integrate velocity to get position, using $x(0)=x_0$.' },
    ],
    realWorld: [
      { title: 'Braking distance', text: 'A car braking at constant deceleration follows this parabola; doubling initial speed roughly quadruples stopping distance.' },
      { title: 'Free fall', text: 'Dropping or throwing an object near Earth\'s surface is this equation with $a = -9.81\\ \\text{m/s}^2$.' },
      { title: 'Elevators and trains', text: 'Comfortable constant-acceleration profiles are designed using exactly this position-time relationship.' },
      { title: 'Rocket ascent (early phase)', text: 'Before fuel burn changes mass significantly, a rocket\'s early ascent is well modeled by constant acceleration.' },
    ],
  },
  {
    id: 'velocity-time-area',
    title: 'Area under a velocity-time graph is displacement',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`\Delta x = \int_a^b v(t)\,dt`,
    summary: 'The shaded area between a velocity curve and the time axis is exactly how far the object has travelled.',
    concepts: ['velocity', 'displacement', 'area-under-curve', 'integral'],
    prerequisites: ['area-under-curve', 'kinematics-constant-acceleration'],
    related: ['kinematics-constant-acceleration', 'fundamental-theorem'],
    visualization: { type: 'function-plot', options: { expr: 'v0 + acc*x', domain: [0, 12], range: [-10, 20], mode: 'area' } },
    parameters: {
      v0: { label: 'initial velocity v₀', min: -8, max: 10, step: 0.5, value: -4, unit: 'm/s' },
      acc: { label: 'acceleration', min: -3, max: 3, step: 0.2, value: 1.5, unit: 'm/s²' },
      a: { label: 'a (start time)', min: 0, max: 11, step: 0.2, value: 0, unit: 's' },
      b: { label: 'b (end time)', min: 0, max: 12, step: 0.2, value: 8, unit: 's' },
    },
    variables: [
      { symbol: 'v(t)', meaning: 'velocity as a function of time' },
      { symbol: r`\Delta x`, meaning: 'net displacement — the signed area' },
      { symbol: 'a, b', meaning: 'start and end times of the interval considered' },
    ],
    explanation: {
      intuition: [
        'Drag $b$ across the region where $v_0 + \\text{acc}\\cdot t$ is negative: the shading appears below the axis and the running displacement readout goes down — moving backward counts as negative area, subtracting from progress rather than adding to it.',
        'Keep dragging $b$ past the point where the line crosses zero: now the shading appears above the axis too, and the positive area starts cancelling the earlier negative area. If the object reverses and retraces its path exactly, the two shaded regions can cancel completely — zero net displacement even though it clearly moved.',
      ],
      formal: [
        '$\\Delta x = \\int_a^b v(t)\\,dt$; regions above the axis contribute positively, regions below contribute negatively.',
        'This is exactly the Fundamental Theorem of Calculus applied to $v = \\dot x$: displacement is the antiderivative of velocity, evaluated between the bounds.',
      ],
      advanced: ['Total distance travelled (odometer reading, always non-negative) is instead $\\int_a^b |v(t)|\\,dt$ — splitting the interval at every sign change of $v$ and adding the absolute value of each piece\'s area. Displacement and distance agree only when the object never reverses direction.'],
    },
    derivation: [
      { tex: r`v(t) = \frac{dx}{dt}`, note: 'Velocity is defined as the rate of change of position.' },
      { tex: r`\int_a^b v(t)\,dt = \int_a^b \frac{dx}{dt}\,dt = x(b) - x(a)`, note: 'Apply the Fundamental Theorem of Calculus.' },
      { tex: r`\Delta x = x(b) - x(a)`, note: 'This difference is, by definition, the net displacement over $[a,b]$.' },
    ],
    realWorld: [
      { title: 'Trip planning', text: 'GPS devices integrate measured speed over time to compute total distance travelled.' },
      { title: 'Sports analytics', text: 'A sprinter\'s velocity curve, integrated, gives split distances at any point in the race.' },
      { title: 'Air traffic and shipping', text: 'Flight or voyage displacement is computed by integrating velocity logs, accounting for any backtracking.' },
      { title: 'Robotics odometry', text: 'Wheeled robots estimate position by integrating wheel-speed sensor readings over time.' },
    ],
  },
  {
    id: 'work-and-energy',
    title: 'Work as the area under a force curve',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`W = \int_0^x F(x')\,dx' = \tfrac12 k x^2`,
    summary: 'Stretching a spring takes more force the further you pull; the work done is the area under that rising force line.',
    concepts: ['work', 'spring-force', 'hookes-law', 'area-under-curve'],
    prerequisites: ['area-under-curve'],
    related: ['velocity-time-area', 'kinetic-and-potential-energy'],
    visualization: { type: 'function-plot', options: { expr: 'k*x', domain: [0, 10], range: [0, 30], mode: 'area' } },
    parameters: {
      k: { label: 'spring constant k', min: 0.2, max: 4, step: 0.1, value: 1.5, unit: 'N/m' },
      a: { label: 'a (start displacement)', min: 0, max: 8, step: 0.2, value: 0, unit: 'm' },
      b: { label: 'b (end displacement)', min: 0, max: 10, step: 0.2, value: 5, unit: 'm' },
    },
    variables: [
      { symbol: 'F = kx', meaning: 'spring restoring force, proportional to stretch (Hooke\'s law)' },
      { symbol: 'k', meaning: 'spring stiffness' },
      { symbol: 'W', meaning: 'work done stretching from $a$ to $b$ — the shaded area' },
    ],
    explanation: {
      intuition: [
        'Drag $b$ outward from $a=0$: the force line rises steadily and the shaded triangle grows — not just wider but taller too, so the area (and hence the work) grows faster than the displacement itself.',
        'Stiffen the spring by raising $k$: the same stretch now needs a taller triangle of force, so the work to reach any given displacement increases in direct proportion to $k$ — a stiffer spring stores more energy for the same stretch.',
      ],
      formal: [
        '$W = \\int_0^x kx\'\\,dx\' = \\tfrac12 kx^2$ — the area of a triangle with base $x$ and height $kx$.',
        'This work is stored as elastic potential energy: $U(x) = \\tfrac12 kx^2$.',
      ],
      advanced: ['Because $F=kx$ is linear, the work-displacement relationship is quadratic; for a general nonlinear restoring force $F(x)$, the stored energy is still $U(x)=\\int_0^x F(x\')dx\'$, but the shape of $U$ mirrors whatever nonlinearity $F$ has — a hardening spring ($F$ growing faster than linear) stores energy that rises faster than quadratically.'],
    },
    derivation: [
      { tex: r`F(x') = kx'`, note: "Hooke's law: restoring force proportional to stretch." },
      { tex: r`W = \int_0^x F(x')\,dx' = \int_0^x kx'\,dx'`, note: 'Work is the accumulated force over the displacement.' },
      { tex: r`W = \left[\tfrac12 kx'^2\right]_0^x = \tfrac12 kx^2`, note: 'Evaluate the integral — the familiar spring potential energy.' },
    ],
    realWorld: [
      { title: 'Archery and catapults', text: 'Drawing a bow or catapult stores elastic energy exactly as $\\tfrac12 kx^2$, released as kinetic energy on firing.' },
      { title: 'Vehicle suspensions', text: 'Springs and shock absorbers store and dissipate energy according to this same work-area relationship.' },
      { title: 'Mattresses and trampolines', text: 'Elastic materials compress under load, storing energy proportional to the square of the compression.' },
      { title: 'Molecular bonds', text: 'Near equilibrium, chemical bond potential energy is often approximated as this same quadratic (harmonic) form.' },
    ],
  },
  {
    id: 'kinetic-and-potential-energy',
    title: 'Kinetic energy and why speed matters so much',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`KE = \tfrac12 m v^2`,
    summary: 'Kinetic energy grows with the square of speed, not speed itself — small increases in speed cost disproportionately more energy to produce or absorb.',
    concepts: ['kinetic-energy', 'potential-energy', 'derivative'],
    prerequisites: ['derivative', 'work-and-energy'],
    related: ['work-and-energy', 'momentum-and-impulse'],
    visualization: { type: 'function-plot', options: { expr: '0.5*m*x^2', domain: [0, 12], range: [-4, 80], mode: 'tangent' } },
    charts: [{ title: 'Gravitational potential energy vs height', xLabel: 'height h (m)', yLabel: 'PE (J)', domain: [0, 12], series: [{ label: 'PE = m·g·h', expr: 'm*9.81*x' }] }],
    parameters: {
      m: { label: 'mass m', min: 0.5, max: 5, step: 0.1, value: 1, unit: 'kg' },
      x: { label: 'speed v', min: 0, max: 12, step: 0.05, value: 6, unit: 'm/s' },
    },
    variables: [
      { symbol: 'm', meaning: 'mass of the object' },
      { symbol: 'v', meaning: 'speed (the horizontal axis, labelled $x$)' },
      { symbol: 'KE', meaning: 'kinetic energy, $\\tfrac12 mv^2$' },
    ],
    explanation: {
      intuition: [
        'Drag the point from low to high speed: the curve does not rise steadily — it bends upward, and the tangent line gets visibly steeper as you go. That steepening slope means each extra unit of speed adds more energy than the last unit did.',
        'Go from speed $v$ to speed $2v$: the curve\'s height doesn\'t merely double, it quadruples, because $(2v)^2 = 4v^2$. That is the physical reason braking distance from double the speed is roughly four times longer — all that extra kinetic energy has to be removed by the same friction force over a longer stopping distance.',
      ],
      formal: [
        '$KE(v) = \\tfrac12 mv^2$; differentiating, $\\dfrac{d(KE)}{dv} = mv$, the momentum — energy increases fastest exactly where momentum is largest.',
        'The chart shows gravitational potential energy $PE = mgh$, linear in height $h$ — a useful contrast: PE grows proportionally, KE grows quadratically.',
      ],
      advanced: ['Kinetic energy is quadratic in $v$ because it comes from integrating momentum: $KE = \\int_0^v mv\'\\,dv\' = \\tfrac12 mv^2$, the same triangular-area argument as spring work but with momentum $mv$ playing the role of the linear "force". This is also why energy, not momentum, sets stopping distances: momentum absorbed at constant braking force gives a time proportional to $v$, but energy absorbed over a fixed braking force gives a distance proportional to $v^2$.'],
    },
    derivation: [
      { tex: r`F = m\frac{dv}{dt}`, note: "Newton's second law." },
      { tex: r`W = \int F\,dx = \int m\frac{dv}{dt}\,dx = \int mv\,dv`, note: 'Change variables using $dx/dt = v$.' },
      { tex: r`KE = \int_0^v mv'\,dv' = \tfrac12 mv^2`, note: 'Integrate from rest to speed $v$ — the work-energy theorem.' },
    ],
    realWorld: [
      { title: 'Crash safety', text: 'Car crash energy scales with speed squared, which is why small speed limit increases produce disproportionately worse collisions.' },
      { title: 'Wind turbines', text: 'Power available from wind scales with the cube of wind speed, since kinetic energy flux already scales as speed squared times speed.' },
      { title: 'Ballistics', text: 'A bullet\'s destructive energy depends on the square of its muzzle velocity, not just its mass.' },
      { title: 'Sports impacts', text: 'A slightly faster pitch or serve carries much more kinetic energy on impact than the speed increase alone would suggest.' },
    ],
  },
  {
    id: 'momentum-and-impulse',
    title: 'Impulse: the area under a force-time pulse',
    subject: 'physics',
    difficulty: 'university',
    equation: r`J = \int F(t)\,dt = \Delta p`,
    summary: 'A quick, hard push and a slow, gentle shove can deliver the same total change in momentum if the areas under their force-time curves match.',
    concepts: ['impulse', 'momentum', 'area-under-curve'],
    prerequisites: ['area-under-curve', 'newtons-second-law'],
    related: ['kinetic-and-potential-energy', 'velocity-time-area'],
    visualization: { type: 'function-plot', options: { expr: 'Fmax*exp(-((x - 0.5)/w)^2)', domain: [0, 1], range: [0, 12], mode: 'area' } },
    parameters: {
      Fmax: { label: 'peak force Fmax', min: 1, max: 10, step: 0.5, value: 6, unit: 'N' },
      w: { label: 'pulse width w', min: 0.02, max: 0.4, step: 0.01, value: 0.08, unit: 's' },
      a: { label: 'a (start time)', min: 0, max: 0.9, step: 0.02, value: 0, unit: 's' },
      b: { label: 'b (end time)', min: 0.1, max: 1, step: 0.02, value: 1, unit: 's' },
    },
    variables: [
      { symbol: 'F(t)', meaning: 'force applied during the collision, peaking at $F_{\\max}$' },
      { symbol: 'w', meaning: 'how spread out in time the force pulse is' },
      { symbol: 'J', meaning: 'impulse — the shaded area, equal to the change in momentum $\\Delta p$' },
    ],
    explanation: {
      intuition: [
        'Make the pulse narrow (small $w$) and tall (large $F_{\\max}$): a short, sharp force spike. Now widen $w$ and lower $F_{\\max}$ to keep the shaded area roughly the same: a long, gentle push. Both deliver the same impulse — the same change in momentum — even though the peak force is wildly different.',
        'That trade-off is exactly what an airbag or crumple zone exploits: it cannot change how much momentum a crash must remove, but it can spread that same area under the curve over a longer time, which forces the peak force down. Same impulse, much lower peak force on the body.',
      ],
      formal: [
        '$J = \\int_a^b F(t)\\,dt = \\Delta p = m\\Delta v$ — Newton\'s second law integrated over time.',
        'For a fixed impulse $J$, stretching the duration $\\Delta t$ over which it acts lowers the average (and typically the peak) force, since $J \\approx \\bar F \\,\\Delta t$.',
      ],
      advanced: ['This is the same area-preserving trade-off seen in signal processing (a narrow, tall pulse and a wide, short one can have equal integral, i.e. equal "DC" content) — in the limit of $w \\to 0$ with the area held fixed, the force pulse approaches a Dirac delta function, an idealised instantaneous impulse used throughout mechanics and control theory.'],
    },
    derivation: [
      { tex: r`F(t) = m\frac{dv}{dt}`, note: "Newton's second law, instant by instant." },
      { tex: r`J = \int_a^b F(t)\,dt = \int_a^b m\frac{dv}{dt}\,dt = m\int_{v(a)}^{v(b)} dv`, note: 'Change variables from time to velocity.' },
      { tex: r`J = m\big(v(b) - v(a)\big) = \Delta p`, note: 'Impulse equals the resulting change in momentum.' },
    ],
    realWorld: [
      { title: 'Airbags and crumple zones', text: 'Both extend the collision time to reduce peak force for the same necessary change in momentum.' },
      { title: 'Padded flooring and mats', text: 'Gymnastics and martial arts mats extend landing time to reduce impact force on joints.' },
      { title: 'Rocket thrust', text: 'Total impulse delivered by a rocket engine (area under its thrust-time curve) determines the resulting change in the rocket\'s momentum.' },
      { title: 'Follow-through in sports', text: 'Extending contact time in a golf or tennis swing changes the force profile while delivering the same or greater impulse.' },
    ],
  },
  {
    id: 'friction-inclined-plane',
    title: 'Friction on an inclined plane',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`a(\theta) = g(\sin\theta - \mu\cos\theta)`,
    summary: 'An object on a slope stays put as long as friction can match gravity\'s pull along the incline; past a critical angle it cannot, and sliding begins.',
    concepts: ['friction', 'inclined-plane', 'newtons-second-law'],
    prerequisites: ['newtons-second-law', 'linear-equations'],
    related: ['newtons-second-law', 'circular-motion'],
    visualization: { type: 'function-plot', options: { expr: '9.81*(sin(x*pi/180) - mu*cos(x*pi/180))', domain: [0, 90], range: [-6, 10], mode: 'plain' } },
    parameters: {
      mu: { label: 'coefficient of friction μ', min: 0, max: 1.2, step: 0.02, value: 0.4 },
      x: { label: 'incline angle θ', min: 0, max: 90, step: 0.2, value: 30, unit: '°' },
    },
    variables: [
      { symbol: r`\theta`, meaning: 'angle of the incline from horizontal' },
      { symbol: r`\mu`, meaning: 'coefficient of friction between object and surface' },
      { symbol: 'a', meaning: 'net acceleration down the slope (negative means friction wins, it stays put)' },
    ],
    explanation: {
      intuition: [
        'At shallow angles the curve sits below zero: gravity\'s pull along the slope is weaker than the maximum friction can resist, so nothing accelerates — the object is held in place. Drag the angle up and watch the curve rise toward zero.',
        'The root, where the curve crosses zero, is the critical angle: past it, the curve is positive and the object accelerates down the slope. Raise $\\mu$ (rougher surface) and that crossing point pushes to a steeper angle — a higher $\\mu$ buys you a steeper slope before sliding starts.',
      ],
      formal: [
        'Along the incline, $ma = mg\\sin\\theta - \\mu mg\\cos\\theta$, giving $a(\\theta) = g(\\sin\\theta - \\mu\\cos\\theta)$, independent of mass.',
        'The critical (sliding) angle satisfies $a=0$: $\\tan\\theta_c = \\mu$ — a direct, mass-independent measurement of the friction coefficient.',
      ],
      advanced: ['This root-finding structure is identical to the linear-equation and quadratic-root lessons: the physically meaningful boundary (here, the onset of sliding) is precisely where a governing expression crosses zero, and the derivative of $a(\\theta)$ with respect to $\\theta$ tells you how sensitively the sliding onset shifts if $\\mu$ or the incline changes — useful for engineering safety margins on ramps and roofs.'],
    },
    derivation: [
      { tex: r`\sum F_{\parallel} = mg\sin\theta - f`, note: 'Forces along the incline: gravity component down the slope minus friction.' },
      { tex: r`f = \mu N = \mu mg\cos\theta`, note: 'Friction opposes motion, proportional to the normal force $N = mg\\cos\\theta$.' },
      { tex: r`ma = mg\sin\theta - \mu mg\cos\theta \;\Rightarrow\; a = g(\sin\theta - \mu\cos\theta)`, note: 'Apply Newton\'s second law; mass cancels.' },
    ],
    realWorld: [
      { title: 'Wheelchair ramps and roofing codes', text: 'Building codes set maximum slope angles based on friction coefficients of the intended surface material.' },
      { title: 'Vehicle hill-holding', text: 'Parking brakes must overcome exactly this friction-versus-gravity balance on a slope.' },
      { title: 'Conveyor and chute design', text: 'Industrial chutes are angled just past the critical sliding angle so material flows rather than jams.' },
      { title: 'Rock and snow slides', text: 'Natural slopes near their critical friction angle are prone to sudden slides when moisture reduces $\\mu$.' },
    ],
  },
  {
    id: 'circular-motion',
    title: 'Centripetal acceleration',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`a_c = \frac{v^2}{r}`,
    summary: 'Moving in a circle at constant speed still means accelerating — always toward the center, growing fast with speed and shrinking slowly with radius.',
    concepts: ['centripetal-acceleration', 'circular-motion', 'derivative'],
    prerequisites: ['derivative', 'unit-circle'],
    related: ['unit-circle', 'friction-inclined-plane'],
    visualization: { type: 'function-plot', options: { expr: 'x^2/rad', domain: [0, 15], range: [-4, 40], mode: 'tangent' } },
    charts: [{ title: 'Centripetal acceleration vs radius (illustrative, v = 10 m/s)', xLabel: 'radius r (m)', yLabel: 'a_c (m/s²)', domain: [1, 20], marker: 'rad', series: [{ label: 'a_c = 100/r', expr: '100/x' }] }],
    parameters: {
      rad: { label: 'radius r', min: 1, max: 20, step: 0.5, value: 5, unit: 'm' },
      x: { label: 'speed v', min: 0, max: 15, step: 0.05, value: 8, unit: 'm/s' },
    },
    variables: [
      { symbol: 'v', meaning: 'speed along the circular path' },
      { symbol: 'r', meaning: 'radius of the circular path' },
      { symbol: 'a_c', meaning: 'centripetal acceleration, directed toward the center' },
    ],
    explanation: {
      intuition: [
        'Drag $v$ upward on the main curve: it bends upward, and the tangent gets steeper and steeper — doubling speed doesn\'t just double the required acceleration, it quadruples it, since $a_c \\propto v^2$.',
        'Now look at the chart, which instead holds speed fixed and varies radius: it falls, gently at first and then flattening — a tight turn (small $r$) at a given speed demands far more centripetal acceleration than a wide, sweeping one, but the penalty for shrinking the radius further eases off once $r$ is already large.',
      ],
      formal: [
        '$a_c = v^2/r$, directed toward the center of the circular path even though speed is constant, because velocity\'s direction is continuously changing.',
        r`$\dfrac{\partial a_c}{\partial v} = 2v/r$` + ' (quadratic growth with speed) versus $\\dfrac{\\partial a_c}{\\partial r} = -v^2/r^2$ (inverse-square decay with radius).',
      ],
      advanced: ['This follows from differentiating a rotating unit vector: for $\\mathbf r(t) = r(\\cos\\omega t, \\sin\\omega t)$, $\\ddot{\\mathbf r} = -\\omega^2 \\mathbf r$, magnitude $\\omega^2 r = v^2/r$ using $v=\\omega r$ — acceleration is anti-parallel to position, i.e. pointing at the center, purely from the geometry of uniform rotation, with no need to invoke any force by name.'],
    },
    derivation: [
      { tex: r`\mathbf r(t) = r(\cos\omega t,\ \sin\omega t)`, note: 'Position on a circle of radius $r$ with angular speed $\\omega$.' },
      { tex: r`\dot{\mathbf r} = r\omega(-\sin\omega t,\ \cos\omega t), \quad |\dot{\mathbf r}| = r\omega = v`, note: 'Velocity is tangent to the circle with constant magnitude $v = r\\omega$.' },
      { tex: r`\ddot{\mathbf r} = -r\omega^2(\cos\omega t,\ \sin\omega t) = -\omega^2\mathbf r \;\Rightarrow\; |\ddot{\mathbf r}| = \frac{v^2}{r}`, note: 'Acceleration points inward (toward the center) with this magnitude.' },
    ],
    realWorld: [
      { title: 'Roller coaster loops', text: 'Loop radius and speed are engineered together so riders experience a safe, tolerable centripetal acceleration.' },
      { title: 'Road curve banking', text: 'Highway curves are banked based on expected speed and radius to keep required centripetal force within tire friction limits.' },
      { title: 'Satellite orbits', text: 'Gravity supplies exactly the centripetal acceleration needed to keep a satellite in a circular orbit at a given radius and speed.' },
      { title: 'Centrifuges', text: 'Laboratory centrifuges spin samples at small radius but very high speed to reach enormous centripetal accelerations.' },
    ],
  },
  {
    id: 'universal-gravitation',
    title: 'Gravitational field strength with distance',
    subject: 'physics',
    difficulty: 'university',
    equation: r`g(r) = \frac{GM}{r^2}`,
    summary: 'Gravity weakens with the square of distance from a planet\'s center — move twice as far away and feel only a quarter of the pull.',
    concepts: ['gravitation', 'inverse-square-law', 'orbit'],
    prerequisites: ['newtons-second-law'],
    related: ['newtons-second-law', 'circular-motion'],
    visualization: { type: 'function-plot', options: { expr: '3.986e14/(x*1e6)^2', domain: [6.4, 50], range: [0, 10], mode: 'plain' } },
    parameters: {
      x: { label: 'distance from Earth\'s center r', min: 6.4, max: 50, step: 0.1, value: 6.4, unit: 'thousand km' },
    },
    variables: [
      { symbol: 'r', meaning: 'distance from the center of the Earth, in thousands of km' },
      { symbol: 'g(r)', meaning: 'gravitational field strength (acceleration) at that distance' },
      { symbol: 'GM', meaning: 'Earth\'s gravitational parameter, $3.986\\times10^{14}\\ \\text{m}^3/\\text{s}^2$' },
    ],
    explanation: {
      intuition: [
        'Start the point at $r = 6.4$ (Earth\'s surface, roughly): the field is about $9.8\\ \\text{m/s}^2$, familiar as ordinary gravity. Drag outward and the curve drops steeply at first — it does not fall off gently, it plunges, because doubling distance divides the field by four, not two.',
        'Keep dragging out toward geostationary orbit distance (about 42,000 km, i.e. $r\\approx42$): the curve has flattened dramatically, hovering near a small fraction of its surface value. Gravity never reaches zero on this plot, but it becomes vanishingly weak — which is exactly why objects that far out can coast in a stable, slow orbit.',
      ],
      formal: [
        '$g(r) = GM/r^2$: an inverse-square law, so $g$ scales as $1/r^2$.',
        'For a circular orbit, gravity supplies the centripetal acceleration: $GM/r^2 = v^2/r$, giving orbital speed $v = \\sqrt{GM/r}$ — orbits farther out move slower.',
      ],
      advanced: ['The inverse-square form is a geometric consequence of gravity spreading its influence over the surface of an expanding sphere of area $4\\pi r^2$: the same total "flux" of gravitational field lines is divided over an area that grows as $r^2$, which is why every inverse-square law (gravity, electrostatics, light intensity) shares this identical mathematical shape despite describing entirely different physics.'],
    },
    derivation: [
      { tex: r`F = \frac{GMm}{r^2}`, note: "Newton's law of universal gravitation." },
      { tex: r`g = \frac{F}{m} = \frac{GM}{r^2}`, note: 'Field strength is force per unit mass — divide by the test mass $m$.' },
      { tex: r`g(6.4\times10^6\ \text{m}) \approx 9.8\ \text{m/s}^2`, note: 'Evaluated at Earth\'s surface radius, this matches familiar everyday gravity.' },
    ],
    realWorld: [
      { title: 'Satellite altitude planning', text: 'Low Earth orbit versus geostationary orbit trade off gravitational pull, orbital speed and coverage using this exact relationship.' },
      { title: 'Weightlessness in orbit', text: 'Astronauts orbiting close to Earth still feel most of Earth\'s gravity — apparent weightlessness comes from free-fall, not distance, but this curve shows gravity is still strong there.' },
      { title: 'Tides', text: 'The Moon\'s gravitational pull, and its gradient across the Earth, drives ocean tides.' },
      { title: 'Interplanetary trajectories', text: 'Spacecraft trajectory planning depends critically on how gravitational pull weakens with distance from each body.' },
    ],
  },
  {
    id: 'torque-and-levers',
    title: 'Torque balance and the lever',
    subject: 'physics',
    difficulty: 'high-school',
    equation: r`F_1 d_1 = F_2 d_2`,
    summary: 'A lever balances when the turning effect on each side matches — a small force far from the pivot can balance a large force close to it.',
    concepts: ['torque', 'lever', 'equilibrium'],
    prerequisites: ['newtons-second-law'],
    related: ['newtons-second-law', 'circular-motion'],
    visualization: { type: 'function-plot', options: { expr: 'F1*d1/x', domain: [0.3, 10], range: [0, 40], mode: 'plain' } },
    parameters: {
      F1: { label: 'known force F1', min: 5, max: 50, step: 1, value: 20, unit: 'N' },
      d1: { label: 'its distance from pivot d1', min: 0.5, max: 5, step: 0.1, value: 2, unit: 'm' },
      x: { label: 'lever arm for F2, d2', min: 0.3, max: 10, step: 0.05, value: 4, unit: 'm' },
    },
    variables: [
      { symbol: 'F_1, d_1', meaning: 'a known force and its distance from the pivot' },
      { symbol: 'd_2', meaning: 'distance of the balancing force from the pivot (the horizontal axis)' },
      { symbol: 'F_2', meaning: 'force needed at distance $d_2$ to balance the lever' },
    ],
    explanation: {
      intuition: [
        'Drag $d_2$ (labelled $x$) outward, away from the pivot: the required balancing force $F_2$ drops sharply — moving the same force further from the pivot buys a much bigger turning effect, so less force is needed to match $F_1 d_1$.',
        'Push $d_2$ toward the pivot instead and the curve shoots upward: balancing a force close to the pivot with almost no lever arm of your own requires enormous force — the practical reason a long crowbar needs so much less effort than a short one to move the same load.',
      ],
      formal: [
        'Equilibrium requires equal and opposite torques: $F_1 d_1 = F_2 d_2$, so $F_2 = F_1 d_1 / d_2$.',
        'This is a hyperbola in $d_2$: $F_2$ and $d_2$ are inversely proportional for fixed $F_1 d_1$.',
      ],
      advanced: ['This is the special case of torque $\\boldsymbol\\tau = \\mathbf r \\times \\mathbf F$ for forces perpendicular to the lever arm, where the magnitude is simply $rF$; a mechanical advantage of $d_1/d_2$ trades force for distance moved (the lever\'s effort end travels further), so no energy is gained — work in equals work out, a first illustration of the conservation principle behind every simple machine.'],
    },
    derivation: [
      { tex: r`\tau_1 = F_1 d_1, \qquad \tau_2 = F_2 d_2`, note: 'Torque is force times distance from the pivot.' },
      { tex: r`\tau_1 = \tau_2 \quad \text{(equilibrium: no net rotation)}`, note: 'A balanced lever has equal and opposite torques.' },
      { tex: r`F_2 = \frac{F_1 d_1}{d_2}`, note: 'Solve for the balancing force.' },
    ],
    realWorld: [
      { title: 'Crowbars and wrenches', text: 'A longer handle multiplies the turning force you can apply for the same effort.' },
      { title: 'Seesaws', text: 'Two people of different weight balance by sitting at different distances from the pivot.' },
      { title: 'Wheelbarrows', text: 'The load, wheel and handle positions set a mechanical advantage via exactly this torque balance.' },
      { title: 'Bridge and crane design', text: 'Counterweights are placed at calculated distances to balance the torque of a load being lifted.' },
    ],
  },
  {
    id: 'simple-harmonic-motion',
    title: 'Simple harmonic motion',
    subject: 'physics',
    difficulty: 'university',
    equation: r`\ddot x + \omega^2 x = 0, \qquad x(t) = A\cos(\omega t), \quad \omega = \sqrt{k/m}`,
    summary: 'A mass on a spring oscillates with a period that depends only on stiffness and mass — never on how far you pull it back.',
    concepts: ['simple-harmonic-motion', 'differential-equation', 'period'],
    prerequisites: ['derivative', 'work-and-energy'],
    related: ['damped-oscillation-resonance', 'sine-function-parameters'],
    visualization: {
      type: 'function-plot',
      options: { expr: 'A*cos(sqrt(k/m)*x)', domain: [0, 12], range: [-5, 5], mode: 'tangent', showDerivative: true, animate: { param: 'x', speed: 1, loop: [0, 12] } },
    },
    parameters: {
      A: { label: 'amplitude A', min: 0.5, max: 4, step: 0.1, value: 3, unit: 'm' },
      k: { label: 'spring constant k', min: 0.2, max: 4, step: 0.1, value: 1, unit: 'N/m' },
      m: { label: 'mass m', min: 0.2, max: 4, step: 0.1, value: 1, unit: 'kg' },
      x: { label: 'time t', min: 0, max: 12, step: 0.02, value: 0, unit: 's' },
    },
    variables: [
      { symbol: 'A', meaning: 'amplitude — how far the mass is pulled back initially' },
      { symbol: 'k', meaning: 'spring stiffness' },
      { symbol: 'm', meaning: 'oscillating mass' },
      { symbol: r`\omega = \sqrt{k/m}`, meaning: 'angular frequency of oscillation' },
    ],
    explanation: {
      intuition: [
        'Let it animate and watch the tangent line and dashed derivative curve: the derivative (velocity) is zero exactly when position is at its extreme (turning around) and largest exactly when position crosses zero (moving fastest through the middle) — position and velocity are a quarter-cycle out of step.',
        'Change $A$ alone and the oscillation swings wider or narrower, but count the time between peaks — it does not change. Now change $k$ or $m$ instead: the period visibly stretches or compresses. Amplitude sets how far it swings; stiffness and mass set how fast it swings, and only stiffness and mass.',
      ],
      formal: [
        'The equation of motion is $\\ddot x + \\omega^2 x = 0$ with $\\omega = \\sqrt{k/m}$ from $F = -kx = m\\ddot x$; general solution $x(t) = A\\cos(\\omega t + \\varphi)$.',
        'Period $T = 2\\pi/\\omega = 2\\pi\\sqrt{m/k}$ is independent of amplitude $A$ — the defining feature of simple harmonic motion.',
      ],
      advanced: ['Amplitude-independence of the period is special to the exactly linear restoring force $F=-kx$; real springs and pendulums deviate from Hooke\'s law at large displacement, and their period then does depend slightly on amplitude — the isochronism seen here is an idealisation that clock and metronome designers approximate as closely as possible over their working amplitude range.'],
    },
    derivation: [
      { tex: r`F = -kx = m\ddot x \;\Rightarrow\; \ddot x + \frac{k}{m}x = 0`, note: "Hooke's law plus Newton's second law." },
      { tex: r`x(t) = A\cos(\omega t + \varphi), \qquad \omega^2 = k/m`, note: 'Try a sinusoidal solution and substitute back; it satisfies the equation for this $\\omega$.' },
      { tex: r`T = \frac{2\pi}{\omega} = 2\pi\sqrt{\frac{m}{k}}`, note: 'The period is set entirely by $m$ and $k$, not by $A$ or $\\varphi$.' },
    ],
    realWorld: [
      { title: 'Pendulum clocks and metronomes', text: 'Their timekeeping relies on the amplitude-independence of the oscillation period.' },
      { title: 'Vehicle suspension bounce', text: 'A car body on its springs oscillates with a natural frequency set by spring stiffness and vehicle mass.' },
      { title: 'Musical instruments', text: 'Strings, reeds and air columns all oscillate approximately harmonically, setting their pitch.' },
      { title: 'MEMS sensors', text: 'Tiny spring-mass systems in accelerometers and gyroscopes are engineered oscillators governed by this same equation.' },
    ],
  },
  // ---------- waves ----------
  {
    id: 'standing-waves',
    title: 'Standing waves on a string',
    subject: 'waves',
    difficulty: 'university',
    equation: r`y(x,t) = 2A\sin\!\left(\frac{n\pi x}{L}\right)\cos(2\pi f t)`,
    summary: 'Two identical waves travelling in opposite directions add up to a pattern that does not travel at all — fixed nodes, oscillating antinodes.',
    concepts: ['standing-wave', 'harmonic', 'interference', 'node'],
    prerequisites: ['sine-wave', 'unit-circle'],
    related: ['sine-wave', 'interference-and-beats'],
    visualization: {
      type: 'function-plot',
      options: { expr: '2*A*sin(pi*n*x/6)*cos(2*pi*f*t)', domain: [0, 6], range: [-3, 3], mode: 'plain', animate: { param: 't', speed: 1, loop: [0, 10] } },
    },
    parameters: {
      A: { label: 'amplitude A', min: 0.2, max: 2, step: 0.05, value: 1 },
      n: { label: 'harmonic number n', min: 1, max: 6, step: 1, value: 2 },
      f: { label: 'frequency f', min: 0.1, max: 1.5, step: 0.05, value: 0.4, unit: 'Hz' },
      t: { label: 'time t', min: 0, max: 10, step: 0.01, value: 0, unit: 's' },
      x: { label: 'position along string x', min: 0, max: 6, step: 0.02, value: 3, unit: 'm' },
    },
    variables: [
      { symbol: 'L', meaning: 'fixed string length, 6 m (both ends held still)' },
      { symbol: 'n', meaning: 'harmonic number — how many humps fit along the string' },
      { symbol: 'A, f', meaning: 'amplitude and frequency of the oscillation' },
    ],
    explanation: {
      intuition: [
        'Let it animate: every point along the string oscillates up and down in place, but some special points — the nodes — never move at all, while others — the antinodes, halfway between nodes — swing with the largest amplitude. Nothing travels left or right; the whole pattern just breathes in and out.',
        'Increase $n$ one step at a time and count the humps: $n$ humps fit exactly between the two fixed, unmoving ends, so $n=1$ has one big hump, $n=2$ has two smaller ones with a new node in the middle, and so on — only these whole-number fits are allowed, because the string must be motionless at both ends.',
      ],
      formal: [
        r`$y(x,t) = 2A\sin(k_n x)\cos(\omega t)$` + ' where $k_n = n\\pi/L$, a superposition of a right- and left-travelling wave of equal amplitude.',
        'Nodes occur where $\\sin(k_n x) = 0$: $x = 0, L/n, 2L/n, \\dots, L$ — always including both fixed ends.',
      ],
      advanced: ['Standing waves are the normal modes of the string: any physically allowed vibration (with both ends fixed) can be written as a superposition $\\sum_n c_n \\sin(n\\pi x/L)\\cos(2\\pi f_n t + \\varphi_n)$, a Fourier series in space at each instant in time — this is the same decomposition that underlies analysing any complex periodic sound as a sum of pure harmonics.'],
    },
    derivation: [
      { tex: r`y_1 = A\sin(kx - \omega t), \qquad y_2 = A\sin(kx + \omega t)`, note: 'Two identical waves travelling in opposite directions.' },
      { tex: r`y = y_1 + y_2 = A\big[\sin(kx-\omega t) + \sin(kx+\omega t)\big]`, note: 'Superpose them (waves add linearly).' },
      { tex: r`y = 2A\sin(kx)\cos(\omega t)`, note: 'Sum-to-product identity: the space and time dependence factor apart — a standing pattern.' },
    ],
    realWorld: [
      { title: 'Musical strings', text: 'Guitar and piano strings vibrate in standing-wave harmonics, which determine the note and its overtones.' },
      { title: 'Wind instruments', text: 'Air columns in flutes and organ pipes form standing waves with nodes and antinodes set by the pipe\'s open or closed ends.' },
      { title: 'Microwave ovens', text: 'Microwaves form standing waves inside the cavity, which is why food turntables exist — to avoid cold spots at the nodes.' },
      { title: 'Bridge and building resonance', text: 'Structures can develop standing-wave-like vibration modes under periodic loading such as wind or footsteps.' },
    ],
  },
  {
    id: 'interference-and-beats',
    title: 'Interference and beats',
    subject: 'waves',
    difficulty: 'university',
    equation: r`\sin(2\pi f_1 x) + \sin(2\pi f_2 x) = 2\cos\!\left(2\pi\tfrac{f_1-f_2}{2}x\right)\sin\!\left(2\pi\tfrac{f_1+f_2}{2}x\right)`,
    summary: 'Two tones close in frequency do not sound steady together — they beat, swelling and fading at a rate equal to the difference between their frequencies.',
    concepts: ['interference', 'beats', 'superposition'],
    prerequisites: ['sine-wave'],
    related: ['sine-wave', 'standing-waves'],
    visualization: { type: 'function-plot', options: { expr: 'sin(2*pi*f1*x) + sin(2*pi*f2*x)', domain: [0, 4], range: [-2.2, 2.2], mode: 'plain' } },
    parameters: {
      f1: { label: 'frequency f1', min: 5, max: 12, step: 0.1, value: 8, unit: 'Hz' },
      f2: { label: 'frequency f2', min: 5, max: 12, step: 0.1, value: 9, unit: 'Hz' },
      x: { label: 'time t', min: 0, max: 4, step: 0.002, value: 0.5, unit: 's' },
    },
    variables: [
      { symbol: 'f_1, f_2', meaning: 'the two individual frequencies being combined' },
      { symbol: '|f_1 - f_2|', meaning: 'the beat frequency — how often the combined amplitude swells' },
    ],
    explanation: {
      intuition: [
        'With $f_1$ and $f_2$ close together, the sum does not look like a clean sine wave — it looks like a fast wiggle trapped inside a slowly swelling and shrinking envelope. Watch the envelope: it grows to twice the single-tone amplitude where the two waves line up (constructive interference), and nearly cancels to zero where they fall out of step (destructive interference).',
        'Pull $f_1$ and $f_2$ further apart and the envelope pulses faster; bring them closer together and the swelling slows down almost to a standstill. The rate of that swelling is always exactly $|f_1-f_2|$ — the beat frequency, independent of how large $f_1$ and $f_2$ themselves are.',
      ],
      formal: [
        '$\\sin(2\\pi f_1 x)+\\sin(2\\pi f_2 x) = 2\\cos(2\\pi\\tfrac{f_1-f_2}{2}x)\\sin(2\\pi\\tfrac{f_1+f_2}{2}x)$; a fast oscillation at the average frequency, amplitude-modulated by a slow cosine.',
        'The amplitude envelope, $|2\\cos(2\\pi\\tfrac{f_1-f_2}{2}x)|$, repeats with frequency $|f_1-f_2|$ — twice per envelope period since it is an absolute value.',
      ],
      advanced: ['Because the ear responds to the envelope\'s amplitude modulation, not the underlying phase, the perceived beat rate is $|f_1-f_2|$ even though the cosine envelope itself has "frequency" $(f_1-f_2)/2$ — the factor of two comes from the envelope crossing zero (a beat) on both its positive and negative half-cycles.'],
    },
    derivation: [
      { tex: r`\sin A + \sin B = 2\sin\!\left(\frac{A+B}{2}\right)\cos\!\left(\frac{A-B}{2}\right)`, note: 'Sum-to-product trigonometric identity.' },
      { tex: r`A = 2\pi f_1 x, \quad B = 2\pi f_2 x`, note: 'Substitute the two wave phases.' },
      { tex: r`= 2\cos\!\left(2\pi\frac{f_1-f_2}{2}x\right)\sin\!\left(2\pi\frac{f_1+f_2}{2}x\right)`, note: 'A slow envelope at the difference frequency times a fast carrier at the average frequency.' },
    ],
    realWorld: [
      { title: 'Tuning instruments', text: 'Musicians tune by listening for beats between two nearly matched notes and adjusting until the beating slows to zero.' },
      { title: 'Radio heterodyning', text: 'Mixing two radio frequencies produces beat frequencies used to shift signals to a more convenient frequency for processing.' },
      { title: 'Doppler radar', text: 'Beat frequencies between transmitted and reflected signals reveal the speed of a moving target.' },
      { title: 'Acoustic dissonance', text: 'Fast, harsh beating between close, out-of-tune frequencies is part of why certain intervals sound dissonant.' },
    ],
  },
  {
    id: 'damped-oscillation-resonance',
    title: 'Damped oscillation and resonance',
    subject: 'waves',
    difficulty: 'university',
    equation: r`x(t) = Ae^{-\gamma t}\cos(\omega t)`,
    summary: 'Friction or resistance drains energy from an oscillator, shrinking its swings inside a decaying envelope — but driven at just the right frequency, a weakly damped oscillator can still respond enormously.',
    concepts: ['damping', 'resonance', 'oscillator'],
    prerequisites: ['simple-harmonic-motion'],
    related: ['simple-harmonic-motion', 'exponential-growth'],
    visualization: { type: 'function-plot', options: { expr: 'A*exp(-g*x)*cos(w*x)', domain: [0, 12], range: [-4, 4], mode: 'tangent' } },
    charts: [{ title: 'Resonance: response amplitude vs driving frequency', xLabel: 'driving frequency ω (rad/s)', yLabel: 'amplitude', domain: [0, 6], marker: 'w0', series: [{ label: 'F/√((ω0²−ω²)² + (2γω)²)', expr: 'F/sqrt((w0^2 - x^2)^2 + (2*g*x)^2)' }] }],
    parameters: {
      A: { label: 'initial amplitude A', min: 0.5, max: 4, step: 0.1, value: 3 },
      g: { label: 'damping rate γ', min: 0.02, max: 1, step: 0.02, value: 0.2, unit: '1/s' },
      w: { label: 'oscillation angular frequency ω', min: 0.5, max: 6, step: 0.1, value: 3, unit: 'rad/s' },
      x: { label: 'time t', min: 0, max: 12, step: 0.02, value: 3, unit: 's' },
      F: { label: 'driving force amplitude F', min: 0.5, max: 5, step: 0.1, value: 2 },
      w0: { label: 'natural frequency ω0', min: 0.5, max: 6, step: 0.1, value: 3, unit: 'rad/s' },
    },
    variables: [
      { symbol: r`\gamma`, meaning: 'damping rate — how fast the envelope decays' },
      { symbol: r`\omega`, meaning: 'angular frequency of the free oscillation (main plot)' },
      { symbol: r`\omega_0, F`, meaning: 'natural frequency and driving amplitude used in the resonance chart' },
    ],
    explanation: {
      intuition: [
        'Drag the point along the main curve and watch the tangent: the oscillation still swings back and forth, but each successive swing is smaller than the last, trapped inside the shrinking dashed-like envelope $\\pm Ae^{-\\gamma t}$. Raise $\\gamma$ and the whole thing dies out visibly faster, while the oscillation frequency $\\omega$ barely changes.',
        'Now look at the chart: it shows how a driven (pushed) version of this same oscillator responds depending on how fast you drive it. Sweep the driving frequency $x$-axis toward $\\omega_0$ and the response amplitude spikes upward sharply if $\\gamma$ is small — pushing at exactly the system\'s own natural rhythm gets an outsized response, the phenomenon of resonance.',
      ],
      formal: [
        'Free damped oscillation: $\\ddot x + 2\\gamma\\dot x + \\omega_0^2 x = 0$ has solution $x(t)=Ae^{-\\gamma t}\\cos(\\omega t)$ (underdamped case, $\\gamma<\\omega_0$).',
        'Driven steady-state amplitude: $X(\\omega) = F/\\sqrt{(\\omega_0^2-\\omega^2)^2 + (2\\gamma\\omega)^2}$, maximised near $\\omega \\approx \\omega_0$ — sharper and taller the smaller $\\gamma$ is.',
      ],
      advanced: ['The resonance peak\'s width is set by $\\gamma$: the "quality factor" $Q = \\omega_0/2\\gamma$ measures how sharply peaked and long-ringing the resonance is, connecting the time-domain decay envelope seen in the main plot directly to the frequency-domain sharpness seen in the chart — the same $\\gamma$ governs both, one of the clearest examples of a time-frequency uncertainty trade-off in physics.'],
    },
    derivation: [
      { tex: r`\ddot x + 2\gamma\dot x + \omega_0^2 x = 0`, note: 'Add a damping (friction) term proportional to velocity to the harmonic oscillator equation.' },
      { tex: r`x(t) = e^{-\gamma t}\big(C_1\cos\omega t + C_2\sin\omega t\big), \quad \omega = \sqrt{\omega_0^2-\gamma^2}`, note: 'Try $x = e^{\\lambda t}$; the characteristic equation gives complex roots $\\lambda=-\\gamma\\pm i\\omega$ when $\\gamma<\\omega_0$.' },
      { tex: r`x(t) = Ae^{-\gamma t}\cos(\omega t + \varphi)`, note: 'Rewrite the sum of sine and cosine as a single decaying cosine with amplitude $A$ and phase $\\varphi$.' },
    ],
    realWorld: [
      { title: 'Bridges', text: 'The Tacoma Narrows collapse is a famous case of wind-driven oscillation approaching a structure\'s resonant frequency.' },
      { title: 'Radio tuning', text: 'A radio\'s tuning circuit is a resonant LC oscillator selecting one station\'s frequency out of many.' },
      { title: 'Playground swings', text: 'Pumping a swing at its natural frequency builds up amplitude far more effectively than any other rhythm.' },
      { title: 'Shock absorbers', text: 'Vehicle suspensions are deliberately damped to avoid resonant bouncing over bumpy, periodic road surfaces.' },
    ],
  },
]
