import type { Lesson } from './types'

const r = String.raw

export const statistics: Lesson[] = [
  {
    id: 'permutations',
    title: 'Permutations: when order matters',
    subject: 'statistics',
    difficulty: 'beginner',
    equation: r`P(n,k) = \frac{n!}{(n-k)!}`,
    summary: 'How many ways can you line up k things chosen from n, when a different order counts as a different result?',
    concepts: ['counting', 'factorial', 'permutation'],
    prerequisites: [],
    related: ['combinations', 'probability-basics'],
    visualization: { type: 'counting', options: { ordered: true } },
    parameters: {
      n: { label: 'n — items available', min: 1, max: 8, step: 1, value: 4 },
      k: { label: 'k — places to fill', min: 0, max: 8, step: 1, value: 2 },
    },
    variables: [
      { symbol: 'n', meaning: 'how many different items you can choose from' },
      { symbol: 'k', meaning: 'how many places you fill, in order' },
      { symbol: 'n!', meaning: 'n factorial: n × (n−1) × … × 1, the ways to line up all n items' },
    ],
    explanation: {
      intuition: [
        'Look at the arrangements listed below the tokens. With 4 tokens and 2 places you get 12: any of the 4 can go first, then any of the 3 that are left can go second, and 4 × 3 = 12. The pair (1,2) and the pair (2,1) both appear, because here order matters — like first and second place in a race.',
        'Raise $k$ by one and every existing arrangement sprouts $n-k$ new endings, so the count grows very fast. Set $k = n$ and you are lining up everything: that is $n!$.',
      ],
      formal: ['$P(n,k) = n(n-1)\\cdots(n-k+1) = \\dfrac{n!}{(n-k)!}$, with $0! = 1$ so that $P(n,n) = n!$.', 'Permutations count injective maps from a $k$-element set into an $n$-element set.'],
      advanced: ['Stirling’s approximation $n! \\sim \\sqrt{2\\pi n}\\,(n/e)^n$ shows how explosively factorials grow: $\\log n!$ is of order $n \\log n$, which is why brute-force search over orderings becomes hopeless beyond a few dozen items.'],
    },
    derivation: [
      { tex: r`n \times (n-1) \times \cdots \times (n-k+1)`, note: 'Multiply the choices for each place: the pool shrinks by one after every pick.' },
      { tex: r`= \frac{n \times (n-1) \times \cdots \times 1}{(n-k) \times \cdots \times 1}`, note: 'Write the product as a ratio of factorials: the factors from $n-k$ downward cancel.' },
      { tex: r`P(n,k) = \frac{n!}{(n-k)!}`, note: 'The compact formula. For $k = n$ the denominator is $0! = 1$.' },
    ],
    realWorld: [
      { title: 'Passwords and PINs', text: 'A 4-digit PIN with no repeated digit has P(10,4) = 5040 possibilities; with repeats allowed it is 10⁴ = 10 000.' },
      { title: 'Race podiums', text: 'Gold, silver and bronze among 8 runners can be awarded in P(8,3) = 336 ways.' },
      { title: 'Scheduling', text: 'Ordering 10 tasks gives 10! ≈ 3.6 million schedules — which is why planners rely on heuristics.' },
    ],
  },
  {
    id: 'combinations',
    title: 'Combinations: when order does not matter',
    subject: 'statistics',
    difficulty: 'beginner',
    equation: r`C(n,k) = \binom{n}{k} = \frac{n!}{k!\,(n-k)!}`,
    summary: 'How many different groups of k can you form from n items, when the group is all that counts?',
    concepts: ['counting', 'combination', 'binomial-coefficient'],
    prerequisites: ['permutations'],
    related: ['binomial-distribution', 'probability-basics'],
    visualization: { type: 'counting', options: { ordered: false } },
    parameters: {
      n: { label: 'n — items available', min: 1, max: 10, step: 1, value: 5 },
      k: { label: 'k — how many to pick', min: 0, max: 10, step: 1, value: 2 },
    },
    variables: [
      { symbol: 'n', meaning: 'how many different items you can choose from' },
      { symbol: 'k', meaning: 'the size of the group you pick' },
      { symbol: r`\binom{n}{k}`, meaning: 'read “n choose k”: the number of possible groups' },
    ],
    explanation: {
      intuition: [
        'Now (1,2) and (2,1) are the same thing — a team of two, not a ranking. Compare with the permutations lesson: with $n = 5$, $k = 2$ there were 20 ordered pairs but only 10 groups, because every group of 2 had been counted twice (once per ordering).',
        'That is the whole idea: count the ordered arrangements, then divide by the $k!$ ways each group can be shuffled. Notice the symmetry too — choosing 2 of 5 to take is the same as choosing 3 of 5 to leave behind, so $C(5,2) = C(5,3)$.',
      ],
      formal: ['$\\dbinom{n}{k} = \\dfrac{P(n,k)}{k!} = \\dfrac{n!}{k!\\,(n-k)!}$; the symmetry $\\dbinom{n}{k} = \\dbinom{n}{n-k}$ follows at once.', 'Pascal’s rule $\\dbinom{n}{k} = \\dbinom{n-1}{k-1} + \\dbinom{n-1}{k}$: either the last item is in the group or it is not.'],
      advanced: ['The binomial theorem $(a+b)^n = \\sum_k \\binom{n}{k} a^k b^{n-k}$ names these numbers: they count how many of the $2^n$ expansion terms have exactly $k$ factors of $a$. Summing the row gives $\\sum_k \\binom{n}{k} = 2^n$, the number of subsets of an $n$-set.'],
    },
    derivation: [
      { tex: r`P(n,k) = \frac{n!}{(n-k)!}`, note: 'Start with ordered selections.' },
      { tex: r`\text{each group of } k \text{ appears } k! \text{ times}`, note: 'Every group can be written in $k!$ orders, and each order was counted separately.' },
      { tex: r`\binom{n}{k} = \frac{P(n,k)}{k!} = \frac{n!}{k!\,(n-k)!}`, note: 'Divide to count each group exactly once.' },
    ],
    realWorld: [
      { title: 'Lotteries', text: 'Choosing 6 numbers from 49: C(49,6) = 13 983 816 tickets, so one ticket wins the jackpot with probability 1 in 14 million.' },
      { title: 'Poker hands', text: 'There are C(52,5) = 2 598 960 five-card hands; counting the hands of each type gives their probabilities.' },
      { title: 'Teams and committees', text: 'Picking a 3-person committee from 12 colleagues: C(12,3) = 220 possible committees.' },
      { title: 'Genetics and sampling', text: 'How many ways a sample of 10 can be drawn from a population of 1000 decides how precise a survey can be.' },
    ],
  },
  {
    id: 'probability-basics',
    title: 'What probability means',
    subject: 'statistics',
    difficulty: 'beginner',
    equation: r`P(A) = \frac{\text{favourable outcomes}}{\text{all equally likely outcomes}}`,
    summary: 'A probability is a share between 0 and 1. Watch a random experiment and see the share emerge from many trials.',
    concepts: ['probability', 'outcome', 'event', 'law-of-large-numbers'],
    prerequisites: [],
    related: ['law-of-large-numbers', 'combinations'],
    visualization: { type: 'coin-flips', options: {} },
    parameters: {
      p: { label: 'p — chance of success on one trial', min: 0.05, max: 0.95, step: 0.05, value: 0.5 },
      N: { label: 'N — number of trials', min: 20, max: 2000, step: 10, value: 200 },
      speed: { label: 'trials per second', min: 1, max: 200, step: 1, value: 20 },
    },
    variables: [
      { symbol: 'p', meaning: 'the true probability of a success — for a fair coin, 0.5' },
      { symbol: 'N', meaning: 'how many times the experiment is repeated' },
      { symbol: r`\hat p`, meaning: 'the proportion of successes observed so far (orange line)' },
    ],
    explanation: {
      intuition: [
        'Each dot along the top is one trial: orange for success, grey for failure. The orange line is the proportion of successes so far. At the start it jumps around wildly — three heads in a row is nothing unusual — but as trials pile up it calms down and hugs the dashed line at $p$.',
        'Probability is that long-run share. It does not say what the next trial will do; it says what fraction you should expect over many trials. Change $p$ to 0.2 and the line settles at one in five. Press “again”: a different path, the same destination.',
      ],
      formal: ['For equally likely outcomes, $P(A) = |A| / |\\Omega|$. In general $0 \\le P(A) \\le 1$, $P(\\Omega) = 1$, and $P(A \\cup B) = P(A) + P(B)$ for disjoint events.', 'The complement rule $P(A^c) = 1 - P(A)$ often turns a hard count into an easy one.'],
      advanced: ['Kolmogorov’s axioms define a probability space $(\\Omega, \\mathcal{F}, P)$ with $P$ countably additive on a σ-algebra. Long-run frequencies are then a *theorem* (the law of large numbers), not the definition — which is what lets probability apply to one-off events as well as repeatable ones.'],
    },
    derivation: [
      { tex: r`\Omega = \{\text{all outcomes}\}, \quad A \subseteq \Omega`, note: 'List every outcome; an event is a set of outcomes.' },
      { tex: r`P(A) = \frac{|A|}{|\Omega|}`, note: 'When outcomes are equally likely, probability is a ratio of counts — which is where permutations and combinations come in.' },
      { tex: r`\hat p_N = \frac{\text{successes}}{N} \xrightarrow{N \to \infty} p`, note: 'The observed proportion converges to the probability: the law of large numbers.' },
    ],
    realWorld: [
      { title: 'Weather forecasts', text: '“30% chance of rain” means: on days like this one, it rains about 3 times in 10.' },
      { title: 'Insurance', text: 'Premiums are set from the long-run frequency of claims across many similar customers.' },
      { title: 'Quality control', text: 'A factory that finds 2 defects in 1000 items estimates a defect probability of 0.002 — and knows a run of 3 defects can still be luck.' },
    ],
  },
  {
    id: 'law-of-large-numbers',
    title: 'Law of large numbers',
    subject: 'statistics',
    difficulty: 'high-school',
    equation: r`\hat p_N \to p, \qquad \sigma_{\hat p} = \sqrt{\frac{p(1-p)}{N}}`,
    summary: 'Averages settle down as you collect more data — and the formula tells you exactly how fast.',
    concepts: ['law-of-large-numbers', 'standard-error', 'sampling'],
    prerequisites: ['probability-basics'],
    related: ['normal-distribution', 'binomial-distribution'],
    visualization: { type: 'coin-flips', options: {} },
    charts: [{ title: 'Typical error of the proportion shrinks like 1/√N', xLabel: 'N (trials)', yLabel: 'σ of p̂', domain: [1, 2000], marker: 'N', series: [{ label: 'sqrt(p(1−p)/N)', expr: 'sqrt(p*(1-p)/x)' }] }],
    parameters: {
      p: { label: 'p — true probability', min: 0.05, max: 0.95, step: 0.05, value: 0.3 },
      N: { label: 'N — number of trials', min: 20, max: 2000, step: 10, value: 1000 },
      speed: { label: 'trials per second', min: 1, max: 200, step: 1, value: 60 },
    },
    variables: [
      { symbol: r`\hat p_N`, meaning: 'the proportion of successes after N trials' },
      { symbol: r`\sigma_{\hat p}`, meaning: 'the typical distance between the proportion and p — the standard error' },
    ],
    explanation: {
      intuition: [
        'The shaded funnel is where 95% of experiments stay. It is wide at the start — after 10 flips a fair coin often shows 30% or 70% heads — and narrows as $N$ grows. But look at how it narrows: to halve the width you need four times as many trials.',
        'That square-root law is why polls of 1000 people are accurate to about ±3% while polls of 100 are only good to ±10%, and why a casino is sure to profit over a year even though any single night is a gamble.',
      ],
      formal: ['Weak law: for every $\\varepsilon > 0$, $P(|\\hat p_N - p| > \\varepsilon) \\to 0$ as $N \\to \\infty$.', 'Since $\\hat p_N$ is a mean of $N$ independent Bernoulli($p$) variables, $\\mathrm{Var}(\\hat p_N) = p(1-p)/N$, hence $\\sigma_{\\hat p} = \\sqrt{p(1-p)/N}$.'],
      advanced: ['The strong law says $\\hat p_N \\to p$ almost surely. Chebyshev’s inequality gives the weak law directly: $P(|\\hat p_N - p| > \\varepsilon) \\le p(1-p)/(N\\varepsilon^2)$. The central limit theorem sharpens this to the normal band $p \\pm 1.96\\sigma_{\\hat p}$ shown in the picture.'],
    },
    derivation: [
      { tex: r`X_i \in \{0, 1\},\quad E[X_i] = p,\quad \mathrm{Var}(X_i) = p(1-p)`, note: 'One trial: a success (1) with probability $p$.' },
      { tex: r`\mathrm{Var}\!\left(\frac{1}{N}\sum X_i\right) = \frac{N\,p(1-p)}{N^2} = \frac{p(1-p)}{N}`, note: 'Variances of independent trials add; dividing by $N$ divides the variance by $N^2$.' },
      { tex: r`\sigma_{\hat p} = \sqrt{\frac{p(1-p)}{N}} \propto \frac{1}{\sqrt N}`, note: 'The spread of the average shrinks with the square root of the sample size.' },
    ],
    realWorld: [
      { title: 'Opinion polls', text: 'The “margin of error ±3%” of a 1000-person poll is exactly 1.96·√(0.25/1000).' },
      { title: 'Casinos and insurers', text: 'Each bet is uncertain; the average over millions of bets is not. The house edge becomes a guaranteed income.' },
      { title: 'A/B testing', text: 'Deciding whether a new web page converts better needs enough visitors for the funnel to be narrower than the difference you hope to detect.' },
    ],
  },
  {
    id: 'binomial-distribution',
    title: 'Binomial distribution',
    subject: 'statistics',
    difficulty: 'high-school',
    equation: r`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}`,
    summary: 'Repeat a yes/no trial n times. How likely is each possible number of successes?',
    concepts: ['binomial', 'distribution', 'expected-value'],
    prerequisites: ['combinations', 'probability-basics'],
    related: ['poisson-distribution', 'normal-distribution'],
    visualization: { type: 'discrete-dist', options: { kind: 'binomial' } },
    parameters: {
      n: { label: 'n — number of trials', min: 1, max: 60, step: 1, value: 10 },
      p: { label: 'p — chance of success each time', min: 0.02, max: 0.98, step: 0.01, value: 0.5 },
      k: { label: 'k — number of successes', min: 0, max: 60, step: 1, value: 3 },
    },
    variables: [
      { symbol: 'X', meaning: 'the number of successes in n trials' },
      { symbol: r`\binom{n}{k}`, meaning: 'the number of ways to place k successes among n trials' },
      { symbol: r`\mu = np`, meaning: 'the mean: what you get on average' },
      { symbol: r`\sigma = \sqrt{np(1-p)}`, meaning: 'the spread around the mean' },
    ],
    explanation: {
      intuition: [
        'Toss 10 fair coins. Exactly 5 heads is the most likely result, yet it happens only about a quarter of the time — the bars show every possibility at once. Drag to $k = 3$: three heads has probability $\\binom{10}{3}/2^{10} = 120/1024$, and the readout shows exactly that.',
        'Move $p$ to 0.2 and the hill slides left and leans; raise $n$ to 60 and the hill turns into a smooth, symmetric bell. That bell is the normal distribution appearing on its own.',
      ],
      formal: ['$X \\sim \\mathrm{Bin}(n,p)$: $P(X=k) = \\binom{n}{k}p^k(1-p)^{n-k}$ for $k = 0,\\dots,n$; $E[X] = np$, $\\mathrm{Var}(X) = np(1-p)$.', 'The probabilities sum to 1 by the binomial theorem: $\\sum_k \\binom{n}{k}p^k(1-p)^{n-k} = (p + 1 - p)^n = 1$.'],
      advanced: ['De Moivre–Laplace: for large $n$, $\\mathrm{Bin}(n,p) \\approx \\mathcal N(np, np(1-p))$, the first central limit theorem (1733). When $n \\to \\infty$ with $np = \\lambda$ fixed, the binomial tends instead to the Poisson distribution.'],
    },
    derivation: [
      { tex: r`P(\text{one specific sequence with } k \text{ successes}) = p^k (1-p)^{n-k}`, note: 'Independent trials: multiply the probabilities along the sequence.' },
      { tex: r`\text{number of such sequences} = \binom{n}{k}`, note: 'Choose which $k$ of the $n$ positions hold the successes — a combination.' },
      { tex: r`P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}`, note: 'Add up the equally likely sequences.' },
    ],
    realWorld: [
      { title: 'Quality control', text: 'If 2% of parts are faulty, the chance a box of 50 has no faulty part is 0.98⁵⁰ ≈ 36%.' },
      { title: 'Medicine', text: 'A drug that works for 70% of patients cures at least 8 of 10 with probability about 38%.' },
      { title: 'Elections and surveys', text: 'The number of “yes” answers in a sample of n voters is binomial — the basis of every margin of error.' },
      { title: 'Genetics', text: 'The number of children in a family who inherit a recessive trait follows Bin(n, ¼).' },
    ],
  },
  {
    id: 'poisson-distribution',
    title: 'Poisson distribution',
    subject: 'statistics',
    difficulty: 'high-school',
    equation: r`P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}`,
    summary: 'Rare events at a steady average rate: how many will happen in the next hour, page, or square kilometre?',
    concepts: ['poisson', 'rate', 'rare-events'],
    prerequisites: ['binomial-distribution'],
    related: ['normal-distribution', 'exponential-growth'],
    visualization: { type: 'discrete-dist', options: { kind: 'poisson' } },
    parameters: {
      lambda: { label: 'λ — average number per interval', min: 0.1, max: 30, step: 0.1, value: 3 },
      k: { label: 'k — number of events', min: 0, max: 60, step: 1, value: 2 },
    },
    variables: [
      { symbol: 'X', meaning: 'the number of events in one interval' },
      { symbol: r`\lambda`, meaning: 'the average count per interval — also the variance' },
      { symbol: 'e', meaning: 'Euler’s number, 2.718…' },
    ],
    explanation: {
      intuition: [
        'A call centre gets 3 calls a minute on average. Some minutes bring none, some bring six. The bars show how the counts spread: with $\\lambda = 3$, exactly 2 calls has probability $9e^{-3}/2 \\approx 0.224$. Zero calls still happens 5% of the time.',
        'Slide $\\lambda$ down to 0.5 and the distribution piles up at zero — most intervals are empty. Slide it to 20 and it becomes a symmetric bell with spread $\\sqrt{20} \\approx 4.5$: for a Poisson variable the variance equals the mean, so counts of about $\\lambda \\pm \\sqrt\\lambda$ are typical.',
      ],
      formal: ['$X \\sim \\mathrm{Poi}(\\lambda)$: $P(X=k) = \\lambda^k e^{-\\lambda}/k!$ for $k = 0, 1, 2, \\dots$; $E[X] = \\mathrm{Var}(X) = \\lambda$.', 'It is the limit of $\\mathrm{Bin}(n, \\lambda/n)$ as $n \\to \\infty$: many opportunities, each with a tiny chance.'],
      advanced: ['A Poisson process has independent increments and $P(\\text{one event in } dt) = \\lambda\\,dt$; the waiting time between events is then exponential with mean $1/\\lambda$, and the count in any interval of length $T$ is $\\mathrm{Poi}(\\lambda T)$. Superposition and thinning of Poisson processes are again Poisson.'],
    },
    derivation: [
      { tex: r`P(X=k) = \binom{n}{k}\left(\frac{\lambda}{n}\right)^k \left(1 - \frac{\lambda}{n}\right)^{n-k}`, note: 'Split the interval into $n$ tiny slots, each with success chance $\\lambda/n$.' },
      { tex: r`\binom{n}{k}\frac{1}{n^k} \to \frac{1}{k!}, \qquad \left(1 - \frac{\lambda}{n}\right)^{n} \to e^{-\lambda}`, note: 'Let the slots become infinitely fine.' },
      { tex: r`P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}`, note: 'The binomial has become the Poisson.' },
    ],
    realWorld: [
      { title: 'Call centres and web servers', text: 'Arrivals per minute are Poisson — the model used to decide how many staff or servers are needed.' },
      { title: 'Radioactive decay', text: 'Clicks of a Geiger counter per second follow a Poisson distribution with λ set by the sample’s activity.' },
      { title: 'Typos, defects, potholes', text: 'Errors per page, flaws per metre of cable, potholes per kilometre: rare, independent, at a steady rate.' },
      { title: 'Historical data', text: 'Bortkiewicz (1898) showed that deaths by horse-kick in Prussian cavalry corps followed Poisson almost perfectly.' },
    ],
  },
  {
    id: 'mean-and-spread',
    title: 'Mean, variance and standard deviation',
    subject: 'statistics',
    difficulty: 'beginner',
    equation: r`\mu = \frac{1}{n}\sum x_i, \qquad \sigma^2 = \frac{1}{n}\sum (x_i - \mu)^2`,
    summary: 'One number for where the data sits, another for how far it wanders. Drag the point to see how squared distances build the variance.',
    concepts: ['mean', 'variance', 'standard-deviation'],
    prerequisites: [],
    related: ['normal-distribution', 'law-of-large-numbers'],
    visualization: { type: 'function-plot', options: { expr: '(x - m)^2', domain: [-2, 12], range: [-5, 60], mode: 'area' } },
    charts: [{ title: 'Total squared distance from a guessed centre c is smallest at the mean', xLabel: 'guessed centre c', yLabel: 'Σ (xᵢ − c)²', domain: [0, 10], marker: 'm', series: [{ label: 'sum over the data 2, 4, 4, 4, 5, 5, 7, 9', expr: '(2-x)^2+(4-x)^2*3+(5-x)^2*2+(7-x)^2+(9-x)^2' }] }],
    parameters: {
      m: { label: 'guessed centre c', min: 0, max: 10, step: 0.05, value: 5 },
      a: { label: 'data from', min: 0, max: 10, step: 0.1, value: 2 },
      b: { label: 'data to', min: 0, max: 10, step: 0.1, value: 9 },
    },
    variables: [
      { symbol: r`\mu`, meaning: 'the mean — the balance point of the data' },
      { symbol: r`\sigma^2`, meaning: 'the variance — the average squared distance from the mean' },
      { symbol: r`\sigma`, meaning: 'the standard deviation — back in the original units' },
    ],
    explanation: {
      intuition: [
        'Take the data 2, 4, 4, 4, 5, 5, 7, 9. Its mean is 5. The chart below adds up the squared distances from any centre you guess: drag $c$ and the total is smallest exactly at 5. The mean is the centre that the data “pulls” least against.',
        'Divide that smallest total (32) by the 8 values and you get the variance, 4. Take the square root to return to the original units: the standard deviation is 2, so a typical value sits about 2 away from the mean. The curve above shows the squared-distance penalty: small near the centre, punishing far away.',
      ],
      formal: ['$\\mu = \\frac1n\\sum x_i$ minimises $\\sum (x_i - c)^2$ over $c$; the minimum value divided by $n$ is $\\sigma^2$, and $\\sigma = \\sqrt{\\sigma^2}$.', 'Sample variance uses $n - 1$ instead of $n$ (Bessel’s correction) so that it estimates the population variance without bias.'],
      advanced: ['$\\mathrm{Var}(X) = E[X^2] - (E[X])^2$; for independent variables variances add, which is the root of the $1/\\sqrt N$ law. The mean minimises squared error while the median minimises absolute error — a different notion of “centre” with a different sensitivity to outliers.'],
    },
    derivation: [
      { tex: r`S(c) = \sum_i (x_i - c)^2`, note: 'Total squared distance from a candidate centre $c$.' },
      { tex: r`S'(c) = -2\sum_i (x_i - c) = 0 \;\Rightarrow\; c = \frac{1}{n}\sum_i x_i = \mu`, note: 'The minimum is where the derivative vanishes — at the mean.' },
      { tex: r`\sigma^2 = \frac{S(\mu)}{n}, \qquad \sigma = \sqrt{\sigma^2}`, note: 'Variance is the minimal average squared distance; the standard deviation undoes the squaring.' },
    ],
    realWorld: [
      { title: 'Exam results', text: 'Two classes can share a mean of 65 while one has σ = 5 (everyone similar) and the other σ = 20 (a wide range).' },
      { title: 'Finance', text: 'The standard deviation of returns is what investors call volatility, or risk.' },
      { title: 'Manufacturing', text: 'Six-sigma quality means tolerances six standard deviations wide — about 3 defects per million.' },
    ],
  },
  {
    id: 'normal-distribution',
    title: 'The normal distribution',
    subject: 'statistics',
    difficulty: 'high-school',
    equation: r`f(x) = \frac{1}{\sigma\sqrt{2\pi}}\, e^{-\frac{(x-\mu)^2}{2\sigma^2}}`,
    summary: 'The bell curve: where sums of many small random effects end up. The area under it between two values is a probability.',
    concepts: ['normal', 'bell-curve', 'z-score', 'central-limit-theorem'],
    prerequisites: ['mean-and-spread', 'binomial-distribution'],
    related: ['law-of-large-numbers', 'integral'],
    visualization: { type: 'function-plot', options: { expr: 'exp(-(x-mu)^2/(2*s^2))/(s*sqrt(2*pi))', domain: [-4, 16], range: [-0.05, 0.85], mode: 'area' } },
    parameters: {
      mu: { label: 'μ — mean', min: 0, max: 12, step: 0.1, value: 6 },
      s: { label: 'σ — standard deviation', min: 0.5, max: 4, step: 0.05, value: 1.5 },
      a: { label: 'from a', min: -4, max: 16, step: 0.05, value: 4.5 },
      b: { label: 'to b', min: -4, max: 16, step: 0.05, value: 7.5 },
    },
    variables: [
      { symbol: r`\mu`, meaning: 'the centre of the bell' },
      { symbol: r`\sigma`, meaning: 'its width: the distance from the centre to the point where the curve changes from convex to concave' },
      { symbol: r`\int_a^b f`, meaning: 'the shaded area — the probability of landing between a and b' },
    ],
    explanation: {
      intuition: [
        'Heights, measurement errors, exam scores: pile up enough small independent influences and this curve appears. The total area under it is exactly 1, and the shaded part is the probability of a value between $a$ and $b$. With $a$ and $b$ one standard deviation either side of the mean, the shaded area is 0.683.',
        'Widen $\\sigma$ and the bell flattens and spreads, but the area between $\\mu \\pm \\sigma$ stays 68%, between $\\mu \\pm 2\\sigma$ 95%, and between $\\mu \\pm 3\\sigma$ 99.7%. Those three numbers let you judge any bell-shaped data with just a mean and a standard deviation.',
      ],
      formal: ['$X \\sim \\mathcal N(\\mu, \\sigma^2)$ has density $f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-(x-\\mu)^2/2\\sigma^2}$; $P(a \\le X \\le b) = \\int_a^b f$. Standardising $Z = (X-\\mu)/\\sigma$ gives $\\mathcal N(0,1)$.', 'There is no elementary antiderivative; probabilities come from the error function $\\Phi(z) = \\tfrac12\\left[1 + \\mathrm{erf}(z/\\sqrt2)\\right]$ or from tables.'],
      advanced: ['Central limit theorem: if $X_i$ are i.i.d. with mean $\\mu$ and finite variance $\\sigma^2$, then $\\sqrt n\\,(\\bar X_n - \\mu)/\\sigma \\to \\mathcal N(0,1)$ in distribution — whatever the shape of the $X_i$. The normal is also the maximum-entropy distribution for a given mean and variance, and the only stable law with finite variance.'],
    },
    derivation: [
      { tex: r`\int_{-\infty}^{\infty} e^{-x^2/2}\,dx = \sqrt{2\pi}`, note: 'The Gaussian integral (evaluated by squaring it and switching to polar coordinates) fixes the normalising constant.' },
      { tex: r`f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-(x-\mu)^2/2\sigma^2}`, note: 'Shift by $\\mu$, scale by $\\sigma$, divide by the constant so the total area is 1.' },
      { tex: r`P(\mu - \sigma \le X \le \mu + \sigma) = \Phi(1) - \Phi(-1) \approx 0.683`, note: 'The 68–95–99.7 rule follows from the standard normal table.' },
    ],
    realWorld: [
      { title: 'Body measurements', text: 'Adult heights within one population are close to normal — which is how clothing sizes are planned.' },
      { title: 'Measurement error', text: 'Repeated readings of the same quantity scatter normally around the true value; the mean of many readings is more precise by 1/√n.' },
      { title: 'Grading and IQ scores', text: 'Standardised tests are scaled to a normal with a chosen mean and standard deviation (IQ: 100 and 15).' },
      { title: 'Finance and engineering', text: 'Noise in signals, tolerances of parts and daily price changes are all modelled — with care about the tails — as normal.' },
    ],
  },
  {
    id: 'bayes-theorem',
    title: 'Conditional probability and Bayes’ theorem',
    subject: 'statistics',
    difficulty: 'high-school',
    equation: r`P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B)}`,
    summary: 'A test is 99% accurate and yours came back positive. How worried should you be? Usually much less than you think.',
    concepts: ['conditional-probability', 'bayes', 'base-rate'],
    prerequisites: ['probability-basics'],
    related: ['binomial-distribution'],
    visualization: { type: 'bayes-grid', options: {} },
    parameters: {
      prior: { label: 'how common the condition is', min: 0.1, max: 50, step: 0.1, value: 1, unit: '%' },
      sens: { label: 'sensitivity — positives among the ill', min: 50, max: 100, step: 0.5, value: 99, unit: '%' },
      spec: { label: 'specificity — negatives among the healthy', min: 50, max: 100, step: 0.5, value: 95, unit: '%' },
    },
    variables: [
      { symbol: 'P(A)', meaning: 'the prior — how likely the condition was before any test' },
      { symbol: r`P(B \mid A)`, meaning: 'the sensitivity — how often the test is positive when the condition is present' },
      { symbol: r`P(A \mid B)`, meaning: 'the posterior — what you actually want: the chance of the condition given a positive test' },
    ],
    explanation: {
      intuition: [
        'Picture 1000 people. With the starting values, 10 of them have the condition and the test catches almost all of them (about 10 true positives). But among the 990 healthy people, 5% — about 50 — also test positive. So of the 60 or so positive results, only 10 are real: a positive test means roughly a 1 in 6 chance of illness, not 99%.',
        'Drag the divider to make the condition more common and watch the posterior climb: the test has not changed, but the base rate has. This is why screening programmes for rare diseases produce many false alarms and why a second, independent test is so valuable.',
      ],
      formal: ['$P(A \\mid B) = \\dfrac{P(A \\cap B)}{P(B)}$ and $P(B) = P(B \\mid A)P(A) + P(B \\mid A^c)P(A^c)$ (total probability). Substituting gives Bayes’ theorem.', 'In odds form: posterior odds = prior odds × likelihood ratio, with LR = sensitivity / (1 − specificity).'],
      advanced: ['Bayesian inference treats parameters as random: $p(\\theta \\mid \\text{data}) \\propto p(\\text{data} \\mid \\theta)\\,p(\\theta)$. Conjugate priors (Beta for a Bernoulli $p$, Gamma for a Poisson rate) make the update closed-form; in general it is done numerically by MCMC. The base-rate fallacy is the human failure to weight the prior.'],
    },
    derivation: [
      { tex: r`P(A \cap B) = P(A \mid B)\,P(B) = P(B \mid A)\,P(A)`, note: 'The same overlap counted two ways — the top-left block of the grid.' },
      { tex: r`P(B) = P(B \mid A)\,P(A) + P(B \mid A^c)\,P(A^c)`, note: 'All positives: true positives plus false positives.' },
      { tex: r`P(A \mid B) = \frac{P(B \mid A)\,P(A)}{P(B \mid A)\,P(A) + P(B \mid A^c)\,P(A^c)}`, note: 'Divide: the share of positives that are genuine.' },
    ],
    realWorld: [
      { title: 'Medical screening', text: 'Mammography, PSA and prenatal tests all suffer from low base rates; results are interpreted with Bayes.' },
      { title: 'Spam filters', text: 'The probability an email is spam given its words is updated word by word — “naive Bayes”.' },
      { title: 'Courts and forensics', text: 'A DNA match probability of 1 in a million is not a 1-in-a-million chance of innocence when millions of people were searched: the prosecutor’s fallacy.' },
      { title: 'Self-driving cars', text: 'Sensor readings update the car’s belief about where obstacles are, frame by frame, with exactly this rule.' },
    ],
  },
  {
    id: 'expected-value',
    title: 'Expected value',
    subject: 'statistics',
    difficulty: 'beginner',
    equation: r`E[X] = \sum_i x_i\,P(x_i)`,
    summary: 'The average outcome over many repeats — the number that tells you whether a game, an insurance policy or a bet is worth it.',
    concepts: ['expected-value', 'average', 'fair-game'],
    prerequisites: ['probability-basics'],
    related: ['mean-and-spread', 'binomial-distribution'],
    visualization: { type: 'function-plot', options: { expr: 'x*w - (1-x)*c', domain: [0, 1], range: [-12, 12], mode: 'plain' } },
    charts: [{ title: 'Long-run average winnings per play against the win probability', xLabel: 'p (chance of winning)', yLabel: 'expected gain', domain: [0, 1], marker: 'x', series: [{ label: 'p·w − (1−p)·c', expr: 'x*w - (1-x)*c' }, { label: 'fair game (zero)', expr: '0*x' }] }],
    parameters: {
      x: { label: 'p — chance of winning', min: 0, max: 1, step: 0.01, value: 0.4 },
      w: { label: 'w — amount won', min: 0, max: 20, step: 0.5, value: 10 },
      c: { label: 'c — amount lost otherwise', min: 0, max: 20, step: 0.5, value: 5 },
    },
    variables: [
      { symbol: 'X', meaning: 'the random gain from one play' },
      { symbol: r`x_i`, meaning: 'a possible outcome (win w or lose c)' },
      { symbol: r`P(x_i)`, meaning: 'its probability' },
    ],
    explanation: {
      intuition: [
        'You win 10 with probability 0.4, otherwise you lose 5. Over 100 plays you expect about 40 wins (+400) and 60 losses (−300): +100 in total, +1 per play. That per-play figure is the expected value, $0.4 \\times 10 - 0.6 \\times 5 = 1$. Drag the point: where the line crosses zero the game is fair.',
        'Every lottery, casino game and insurance policy is designed so this number favours the house. The expected value of a €2 lottery ticket is typically about €1 — you pay €1 per ticket, on average, for the excitement.',
      ],
      formal: ['$E[X] = \\sum_i x_i P(X = x_i)$ for discrete $X$; $E[X] = \\int x f(x)\\,dx$ for continuous $X$. Linearity: $E[aX + bY] = aE[X] + bE[Y]$ always holds, independent or not.', 'The law of large numbers says the average of many plays converges to $E[X]$.'],
      advanced: ['Expected value alone ignores risk: the St Petersburg game has infinite expectation yet nobody would pay much to play. Utility theory (Bernoulli, von Neumann–Morgenstern) replaces $E[X]$ with $E[u(X)]$ for a concave $u$, and the Kelly criterion shows that maximising expected *log* wealth is what grows a bankroll fastest.'],
    },
    derivation: [
      { tex: r`\text{in } N \text{ plays: about } Np \text{ wins and } N(1-p) \text{ losses}`, note: 'Use the long-run proportions.' },
      { tex: r`\text{total} \approx Np\,w - N(1-p)\,c`, note: 'Add the gains and subtract the losses.' },
      { tex: r`E[X] = \frac{\text{total}}{N} = p\,w - (1-p)\,c`, note: 'Per play: each outcome weighted by its probability.' },
    ],
    realWorld: [
      { title: 'Insurance', text: 'A premium is the expected payout plus a margin: many pay a little so that the few who suffer are paid.' },
      { title: 'Lotteries and casinos', text: 'Roulette returns 97.3% of stakes on average — an expected loss of 2.7% per spin.' },
      { title: 'Decisions under uncertainty', text: 'Should a company launch a product? Multiply each scenario’s profit by its probability and add.' },
    ],
  },
]
